import { handleGetTaxLedgerEntriesAudit } from "@voyzu-modules/core/company-reports/tax-ledger-entries-audit/server";
import { handleGetInventoryLedgerEntriesAudit } from "@voyzu-modules/core/company-reports/inventory-ledger-entries-audit/server";
import { handleGetApSubledgerEntriesAudit } from "@voyzu-modules/core/company-reports/ap-subledger-entries-audit/server";
import { handleGetArSubledgerEntriesAudit } from "@voyzu-modules/core/company-reports/ar-subledger-entries-audit/server";
import { handleGetTaxActivityReconciliation } from "@voyzu-modules/core/company-reports/tax-activity-reconciliation/server";
import { handleGetTaxActivity } from "@voyzu-modules/core/company-reports/tax-activity/server";
import { handleGetProfitLoss, handleGetProfitLossAnalysis } from "@voyzu-modules/core/company-reports/profit-loss/server";
import { handleGetFinancialIntegrity } from "@voyzu-modules/core/company-reports/financial-integrity/server";
import { handleGetJournalEntries } from "@voyzu-modules/core/company-reports/journal-entries/server";
import { handleGetBankCashMovement } from "@voyzu-modules/core/company-reports/bank-cash-movement/server";
import { handleGetTaxPosition } from "@voyzu-modules/core/company-reports/tax-position/server";
import { handleGetTrialBalance } from "@voyzu-modules/core/company-reports/trial-balance/server";
import { handleGetBalanceSheet, handleListFinancialYears, handleGetBalanceSheetPdf } from "@voyzu-modules/core/company-reports/balance-sheet/server";
import { arrayOf, dtoRef } from "@voyzu/types/api";

export const companyReportsModule = {
  id: "voyzu.companyReports",
  name: "Company Reports",
  pageRoutes: {
    balanceSheet: {
      id: "voyzu.companyReports.page.balanceSheet",
      pageTitle: "Balance Sheet",
      helpUrl: "modules-help/company-ledger/balance-sheet",
    },
    trialBalance: {
      id: "voyzu.companyReports.page.trialBalance",
      pageTitle: "Trial Balance",
      helpUrl: "modules-help/company-ledger/trial-balance",
    },
    taxPosition: {
      id: "voyzu.companyReports.page.taxPosition",
      pageTitle: "Tax Position",
      helpUrl: "modules-help/company-ledger/tax-position",
    },
    bankCashMovement: {
      id: "voyzu.companyReports.page.bankCashMovement",
      pageTitle: "Bank / Cash Movement",
      helpUrl: "modules-help/company-ledger/bank-cash-movement",
    },
    journalEntries: {
      id: "voyzu.companyReports.page.journalEntries",
      pageTitle: "Journal Entries",
      helpUrl: "modules-help/company-ledger/journal-entries-report",
    },
    accountActivity: {
      id: "voyzu.companyReports.page.accountActivity",
      pageTitle: "Account Activity",
      helpUrl: "modules-help/company-ledger/account-activity",
    },
    financialIntegrity: {
      id: "voyzu.companyReports.page.financialIntegrity",
      pageTitle: "Financial Integrity",
      helpUrl: "modules-help/company-ledger/financial-integrity",
    },
    profitLoss: {
      id: "voyzu.companyReports.page.profitLoss",
      pageTitle: "Profit & Loss",
      helpUrl: "modules-help/company-ledger/profit-loss",
    },
    profitLossAnalysis: {
      id: "voyzu.companyReports.page.profitLossAnalysis",
      pageTitle: "Profit & Loss Analysis",
      helpUrl: "modules-help/company-ledger/profit-loss-analysis",
    },
    taxActivity: {
      id: "voyzu.companyReports.page.taxActivity",
      pageTitle: "Tax Return",
      helpUrl: "modules-help/company-ledger/tax-return",
    },
    taxActivityReconciliation: {
      id: "voyzu.companyReports.page.taxActivityReconciliation",
      pageTitle: "Tax Reconciliation",
      helpUrl: "modules-help/company-ledger/tax-reconciliation",
    },
    arSubledgerEntriesAudit: {
      id: "voyzu.companyReports.page.arSubledgerEntriesAudit",
      pageTitle: "AR Subledger Entries",
      helpUrl: "modules-help/company-ledger/ar-subledger-entries-report",
    },
    apSubledgerEntriesAudit: {
      id: "voyzu.companyReports.page.apSubledgerEntriesAudit",
      pageTitle: "AP Subledger Entries",
      helpUrl: "modules-help/company-ledger/ap-subledger-entries-report",
    },
    inventoryLedgerEntriesAudit: {
      id: "voyzu.companyReports.page.inventoryLedgerEntriesAudit",
      pageTitle: "Inventory Ledger Entries",
      helpUrl: "modules-help/company-ledger/inventory-ledger-entries-report",
    },
    taxLedgerEntriesAudit: {
      id: "voyzu.companyReports.page.taxLedgerEntriesAudit",
      pageTitle: "Tax Ledger Entries",
      helpUrl: "modules-help/company-ledger/tax-ledger-entries-report",
    },
  },
  apiDefinitions: {
    balanceSheet: {
      method: "GET",
      path: "/finance/[companyCode]/reports/balance-sheet",
      handler: (request: any) => handleGetBalanceSheet(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Balance Sheet",
        description: "Balance Sheet Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("BalanceSheetResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    balanceSheetPdf: {
      method: "GET",
      path: "/finance/[companyCode]/reports/balance-sheet/pdf",
      handler: (request: any) => handleGetBalanceSheetPdf(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Get balance sheet PDF",
        description: "Generates a balance sheet PDF for the selected company and reporting options.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Generated balance sheet PDF.", contentType: "application/pdf" }, "400": { description: "Required query parameters are missing or invalid.", schema: dtoRef("InputValidationErrorResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } }
      },
    },
    financialYears: {
      method: "GET",
      path: "/finance/[companyCode]/reports/financial-years",
      handler: (request: any) => handleListFinancialYears(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Financial Years",
        description: "Financial Years Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: arrayOf(dtoRef("FinancialYearResponseDto")) }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    trialBalance: {
      method: "GET",
      path: "/finance/[companyCode]/reports/trial-balance",
      handler: (request: any) => handleGetTrialBalance(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Trial Balance",
        description: "Trial Balance Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("TrialBalanceResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    taxPosition: {
      method: "GET",
      path: "/finance/[companyCode]/reports/tax-position",
      handler: (request: any) => handleGetTaxPosition(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Tax Position",
        description: "Tax Position Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("TaxPositionResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    bankCashMovement: {
      method: "GET",
      path: "/finance/[companyCode]/reports/bank-cash-movement",
      handler: (request: any) => handleGetBankCashMovement(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Bank Cash Movement",
        description: "Bank Cash Movement Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("BankCashMovementResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    journalEntries: {
      method: "GET",
      path: "/finance/[companyCode]/reports/journal-entries",
      handler: (request: any) => handleGetJournalEntries(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Journal Entries",
        description: "Journal Entries Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("JournalEntriesResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    financialIntegrity: {
      method: "GET",
      path: "/finance/[companyCode]/reports/financial-integrity",
      handler: (request: any) => handleGetFinancialIntegrity(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Financial Integrity",
        description: "Financial Integrity Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("FinancialIntegrityResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    profitLoss: {
      method: "GET",
      path: "/finance/[companyCode]/reports/profit-loss",
      handler: (request: any) => handleGetProfitLoss(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Profit Loss",
        description: "Profit Loss Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("ProfitLossResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    profitLossAnalysis: {
      method: "GET",
      path: "/finance/[companyCode]/reports/profit-loss-analysis",
      handler: (request: any) => handleGetProfitLossAnalysis(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Profit Loss Analysis",
        description: "Profit Loss Analysis Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("ProfitLossAnalysisResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    taxActivity: {
      method: "GET",
      path: "/finance/[companyCode]/reports/tax-activity",
      handler: (request: any) => handleGetTaxActivity(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Tax Activity",
        description: "Tax Activity Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("TaxActivityResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    taxActivityReconciliation: {
      method: "GET",
      path: "/finance/[companyCode]/reports/tax-activity-reconciliation",
      handler: (request: any) => handleGetTaxActivityReconciliation(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Tax Activity Reconciliation",
        description: "Tax Activity Reconciliation Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("TaxActivityReconciliationResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    arSubledgerEntriesAudit: {
      method: "GET",
      path: "/finance/[companyCode]/reports/ar-subledger-entries-audit",
      handler: (request: any) => handleGetArSubledgerEntriesAudit(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Subledger Entries Audit",
        description: "AR Subledger Entries Audit Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("ArSubledgerEntriesAuditResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    apSubledgerEntriesAudit: {
      method: "GET",
      path: "/finance/[companyCode]/reports/ap-subledger-entries-audit",
      handler: (request: any) => handleGetApSubledgerEntriesAudit(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Subledger Entries Audit",
        description: "AP Subledger Entries Audit Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("ApSubledgerEntriesAuditResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    inventoryLedgerEntriesAudit: {
      method: "GET",
      path: "/finance/[companyCode]/reports/inventory-ledger-entries-audit",
      handler: (request: any) => handleGetInventoryLedgerEntriesAudit(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Inventory Ledger Entries Audit",
        description: "Inventory Ledger Entries Audit Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("InventoryLedgerEntriesAuditResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
    taxLedgerEntriesAudit: {
      method: "GET",
      path: "/finance/[companyCode]/reports/tax-ledger-entries-audit",
      handler: (request: any) => handleGetTaxLedgerEntriesAudit(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Tax Ledger Entries Audit",
        description: "Tax Ledger Entries Audit Company Reports.",
        tags: ["Company Reports"],
        responses: { "200": { description: "Successful response.", schema: dtoRef("TaxLedgerEntriesAuditResponseDto") }, "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") } },
      },
    },
  }
} as const;
