"use client";
import { useState, useTransition } from "react";
import { useRouter, usePathname } from "next/navigation";
import { AuditPanel } from "@voyzu/ui-business-components";
import { DetailBackButton, detailLinkWithBackContext } from "@voyzu/ui-surface/client";
import { Badge, Breadcrumbs, Button, ConfirmDialog, DropdownMenu, Input, Textarea, Toast, ValidationAlert, useFormValidation, required, maxLength } from "@voyzu/ui-components";
import layout from "@voyzu/ui-layout/css-modules/detail.layout.module.css";
import detail from "@voyzu/ui-style/css-modules/detail.module.css";
import typography from "@voyzu/ui-style/css-modules/typography.module.css";
import styles from "./product-detail.module.css";
import { ProductModal } from "./ProductModal";
import { configurationMeta, type ProductConfigurationKind, type ProductConfigurationDetail } from "../types/product-configuration.dto";
import { saveConfigurationAction, transitionConfigurationAction } from "../server/actions/product-configuration.actions";
export function ProductConfigurationDetailView({ initial, kind }: { initial: ProductConfigurationDetail; kind: ProductConfigurationKind }) {
 const router=useRouter(), pathname=usePathname(), meta=configurationMeta[kind];
 const [record,setRecord]=useState(initial), [name,setName]=useState(initial.name), [description,setDescription]=useState(initial.description), [values,setValues]=useState(initial.values);
 const [error,setError]=useState(""),[toast,setToast]=useState(""),[confirm,setConfirm]=useState(false),[pending,startTransition]=useTransition();
 const [newValue,setNewValue]=useState(""),[editing,setEditing]=useState<{original:string;value:string}|null>(null),[removing,setRemoving]=useState<string|null>(null);
 const validation=useFormValidation(()=>({name:{label:"name",value:name,rules:[required(),maxLength(100)]},description:{label:"description",value:description,rules:[maxLength(2000)]}}));
 const valueValidation=useFormValidation(()=>({value:{label:"value",value:editing?.value??newValue,rules:[required(),maxLength(100),{kind:"format",test:(value)=>!values.some((existing)=>existing!==editing?.original&&existing.toLowerCase()===value.trim().toLowerCase()),message:"Values must be unique"}]}}));
 const save=()=>{setError("");if(!validation.attempt())return;startTransition(async()=>{try{const result=await saveConfigurationAction(kind,{code:record.code,name:name.trim(),description,values},record.code);if(!result.record){setError(result.error??"Unable to save.");return;}setRecord(result.record);setName(result.record.name);setDescription(result.record.description);setValues(result.record.values);validation.reset();setToast(meta.singular+" saved");router.refresh();}catch{setError("Unable to save. Please try again.");}});};
 const transition=(operation:"activate"|"deactivate"|"delete")=>{setError("");startTransition(async()=>{try{const result=await transitionConfigurationAction(kind,[record.code],operation);if(result.error){setError(result.error);return;}if(operation==="delete"){router.push(meta.href);router.refresh();return;}if(result.record)setRecord(result.record);setToast(meta.singular+(operation==="activate"?" activated":" deactivated"));router.refresh();}catch{setError("Unable to update. Please try again.");}});};
 const addValue=()=>{if(!valueValidation.attempt())return;setValues([...values,newValue.trim()]);setNewValue("");valueValidation.reset();};
 return <div className={layout.detailView+" "+layout.detailViewWithStatusRail}>
 <header className={layout.detailHeader}>
 <div className={layout.slotBreadcrumb}><Breadcrumbs/></div>
 <div className={layout.slotTitle}><div className={detail.title}><div className={detail.titleIcon}><span className={"material-symbols-outlined "+detail.titleIconSymbol}>inventory_2</span></div><h1 className={typography.pageTitle+" "+layout.pageTitleResponsive}>{name}</h1></div></div>
 <div className={layout.slotActions}><div className={detail.headerActions}><DetailBackButton fallbackHref={meta.href}/><div className={detail.headerActionSeparator}/><Button variant="secondary" icon="check_circle" disabled={pending||record.status==="ACTIVE"} onClick={()=>transition("activate")}>Activate</Button><Button variant="secondary" icon="block" disabled={pending||record.status==="INACTIVE"} onClick={()=>transition("deactivate")}>Deactivate</Button><div className={detail.headerActionSeparator}/><Button variant="danger" icon="delete" aria-label={"Delete "+meta.singular} disabled={pending} onClick={()=>setConfirm(true)}/></div></div>
 <div className={layout.slotAlert}><ValidationAlert errors={[...(validation.showErrors?validation.errors:[]),...(!editing&&valueValidation.showErrors?valueValidation.errors:[]),...(error?[error]:[])]} visible={validation.showErrors||(!editing&&valueValidation.showErrors)||!!error} onDismiss={()=>{validation.dismiss();valueValidation.dismiss();setError("");}}/></div>
 </header>
 <aside className={layout.statusSection}><section className={detail.card}><span className={typography.fieldLabel}>Status</span><Badge variant="soft" size="x-large" color={record.status==="ACTIVE"?"success":"neutral"}>{record.status}</Badge>{record.usedBy.length>0&&<><span className={typography.fieldLabel}>Usage</span><Badge variant="soft" size="large" color="info">IN USE</Badge></>}</section>
 <AuditPanel id={record.id} creationDate={record.createdAt?new Date(record.createdAt).toISOString():""} updatedDate={record.updatedAt?new Date(record.updatedAt).toISOString():""} auditHref={detailLinkWithBackContext("/settings/audit?entityType=product-"+kind+"&entityId="+record.id,"audit",pathname)} onNavigate={(href)=>router.push(href)}/></aside>
 <main className={layout.mainSection+" "+detail.stack}><section className={detail.card}>
 <div className={detail.cardHeader}><h2 className={typography.sectionHeading+" "+detail.cardHeaderTitle}>{meta.singular} Details</h2><Button variant="secondary" icon="save" disabled={pending} onClick={save}>Save</Button></div>
 <div className={detail.formGrid}><div className={detail.fieldGroup}><label className={typography.fieldLabel} htmlFor="detail-code">Code</label><Input id="detail-code" disabled value={record.code}/></div><div className={detail.fieldGroup}><label className={typography.fieldLabel} htmlFor="detail-name">Name</label><Input id="detail-name" disabled={pending} invalid={validation.hasError("name")} value={name} onChange={(e)=>setName(e.target.value)}/></div></div>
 <div className={detail.fieldGroup}><label className={typography.fieldLabel} htmlFor="detail-description">Description</label><Textarea id="detail-description" disabled={pending} invalid={validation.hasError("description")} value={description} onChange={(e)=>setDescription(e.target.value)}/></div>
 {kind!=="categories"&&<div className={detail.dividedStack}><h3 className={typography.sectionHeading}>Values</h3>
 <div className={styles.optionCard}><div className={detail.cardHeaderActions}><Input aria-label="New value" placeholder="New value" disabled={pending} invalid={!editing&&valueValidation.hasError("value")} value={newValue} onChange={(e)=>setNewValue(e.target.value)}/><Button variant="secondary" icon="add" disabled={pending} onClick={addValue}>Add Value</Button></div></div>
 <table className={detail.table}><thead><tr><th>Value</th><th>Used By</th><th/></tr></thead><tbody>{values.map((value)=><tr key={value}><td>{value}</td><td>{record.valueUsage[value]??0} products</td><td><DropdownMenu alignment="right" trigger={<Button variant="plain" icon="more_horiz" aria-label={value+" actions"} disabled={pending}/>} items={[{value:"edit",label:"Edit",icon:"edit",disabled:(record.valueUsage[value]??0)>0,onSelect:()=>{valueValidation.reset();setEditing({original:value,value});}},{value:"remove",label:"Remove",icon:"delete",disabled:(record.valueUsage[value]??0)>0,onSelect:()=>setRemoving(value)}]}/></td></tr>)}{!values.length&&<tr><td colSpan={3} className={detail.emptyCell}>No values yet.</td></tr>}</tbody></table>
 </div>}
 </section>
 <section className={detail.card}><div className={detail.cardHeader}><h2 className={typography.sectionHeading+" "+detail.cardHeaderTitle}>Used By</h2></div><div className={detail.tableWrap}><table className={detail.table}><thead><tr><th>Product Code</th><th>Name</th></tr></thead><tbody>{record.usedBy.map((product)=><tr key={product.id}><td><a className={typography.link} href={"/commercial/products/"+encodeURIComponent(product.code)}>{product.code}</a></td><td>{product.name}</td></tr>)}{!record.usedBy.length&&<tr><td colSpan={2} className={detail.emptyCell}>No products use this {meta.singular.toLowerCase()}.</td></tr>}</tbody></table></div></section>
 </main>
 {editing&&<ProductModal title="Edit Value" submitLabel="Update Value" pending={pending} onClose={()=>{setEditing(null);valueValidation.reset();}} onSubmit={()=>{if(!valueValidation.attempt())return;setValues(values.map((value)=>value===editing.original?editing.value.trim():value));setEditing(null);valueValidation.reset();}}><ValidationAlert errors={valueValidation.errors} visible={valueValidation.showErrors} onDismiss={valueValidation.dismiss}/><div className={detail.fieldGroup}><label className={typography.fieldLabel} htmlFor="edit-value">Value</label><Input id="edit-value" invalid={valueValidation.hasError("value")} value={editing.value} onChange={(e)=>setEditing({...editing,value:e.target.value})}/></div></ProductModal>}
 <ConfirmDialog isOpen={removing!==null} title="Remove Value" message={"Remove "+removing+"?"} confirmLabel="Remove" confirmVariant="danger" onClose={()=>setRemoving(null)} onConfirm={()=>{setValues(values.filter((value)=>value!==removing));setRemoving(null);}}/>
 <ConfirmDialog isOpen={confirm} title={"Delete "+meta.singular} message={"Permanently delete "+record.name+"?"} confirmLabel="Delete" confirmVariant="danger" onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);transition("delete");}}/>
 <Toast isVisible={!!toast} message={toast} onClose={()=>setToast("")}/>
 </div>;
}
