import Type from "typebox";
import { BusinessRuleErrorResponseDto, ConflictErrorResponseDto, EntityNotFoundErrorResponseDto, InternalServerErrorResponseDto, InputValidationErrorResponseDto } from "@voyzu/types";
import { ItemCodeListRequestDto, ItemCreateRequestDto, ItemListRowDto, ItemOptionsDto, ItemPatchRequestDto, ItemResponseDto } from "./types/item.types";

const skuPath = { sku: { description: "Organization-unique inventory item SKU.", schema: Type.String({ pattern: "^[A-Z0-9][A-Z0-9_-]*$" }) } };
const errors = {
  "400": { description: "Validation failed.", body: InputValidationErrorResponseDto },
  "404": { description: "The item was not found.", body: EntityNotFoundErrorResponseDto },
  "409": { description: "The request conflicts with existing data.", body: ConflictErrorResponseDto },
  "422": { description: "A business rule blocked the operation.", body: BusinessRuleErrorResponseDto },
  "500": { description: "An unexpected server error occurred.", body: InternalServerErrorResponseDto },
} as const;

export const apiDefinitions = {
  list: { method: "GET", path: "/inventory/items", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleList), summary: "List inventory items", description: "Lists inventory items for the selected organization.", tags: ["Inventory Items"], responses: { "200": { description: "Inventory items.", body: Type.Array(ItemListRowDto) }, ...errors } },
  options: { method: "GET", path: "/inventory/items/options", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleOptions), summary: "Get item form options", description: "Returns categories and the next generated SKU for item forms.", tags: ["Inventory Items"], responses: { "200": { description: "Item categories and next generated SKU.", body: ItemOptionsDto }, ...errors } },
  create: { method: "POST", path: "/inventory/items", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleCreate), summary: "Create inventory item", description: "Creates an inventory item in the selected organization.", tags: ["Inventory Items"], request: { contentType: "application/json", body: ItemCreateRequestDto }, responses: { "201": { description: "The created item.", body: ItemResponseDto }, ...errors } },
  get: { method: "GET", path: "/inventory/items/[sku]", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleGet), summary: "Get inventory item", description: "Gets an inventory item by SKU in the selected organization.", tags: ["Inventory Items"], request: { path: skuPath }, responses: { "200": { description: "The inventory item.", body: ItemResponseDto }, ...errors } },
  patch: { method: "PATCH", path: "/inventory/items/[sku]", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handlePatch), summary: "Patch inventory item", description: "Updates writable item details and assembly components.", tags: ["Inventory Items"], request: { path: skuPath, contentType: "application/json", body: ItemPatchRequestDto }, responses: { "200": { description: "The updated item.", body: ItemResponseDto }, ...errors } },
  delete: { method: "DELETE", path: "/inventory/items/[sku]", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleDelete), summary: "Delete inventory item", description: "Deletes an item that has not been used in inventory transactions.", tags: ["Inventory Items"], request: { path: skuPath }, responses: { "204": { description: "Item deleted." }, ...errors } },
  activate: { method: "POST", path: "/inventory/items/[sku]/activate", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleActivate), summary: "Activate inventory item", description: "Changes an inventory item to active status.", tags: ["Inventory Items"], request: { path: skuPath }, responses: { "200": { description: "The activated item.", body: ItemResponseDto }, ...errors } },
  deactivate: { method: "POST", path: "/inventory/items/[sku]/deactivate", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleDeactivate), summary: "Deactivate inventory item", description: "Changes an inventory item to inactive status.", tags: ["Inventory Items"], request: { path: skuPath }, responses: { "200": { description: "The deactivated item.", body: ItemResponseDto }, ...errors } },
  batchActivate: { method: "POST", path: "/inventory/items/batch/activate", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleBatchActivate), summary: "Activate inventory items", description: "Activates the supplied inventory item SKUs.", tags: ["Inventory Items"], request: { contentType: "application/json", body: ItemCodeListRequestDto }, responses: { "200": { description: "Activated items.", body: Type.Array(ItemResponseDto) }, ...errors } },
  batchDeactivate: { method: "POST", path: "/inventory/items/batch/deactivate", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleBatchDeactivate), summary: "Deactivate inventory items", description: "Deactivates the supplied inventory item SKUs.", tags: ["Inventory Items"], request: { contentType: "application/json", body: ItemCodeListRequestDto }, responses: { "200": { description: "Deactivated items.", body: Type.Array(ItemResponseDto) }, ...errors } },
  batchDelete: { method: "POST", path: "/inventory/items/batch/delete", loadHandler: () => import("./server/api/item.http.handlers").then((module) => module.handleBatchDelete), summary: "Delete inventory items", description: "Deletes supplied items that have not been used in inventory transactions.", tags: ["Inventory Items"], request: { contentType: "application/json", body: ItemCodeListRequestDto }, responses: { "204": { description: "Items deleted." }, ...errors } },
} as const;
