import Type from "typebox";
import { BusinessRuleErrorResponseDto, ConflictErrorResponseDto, EntityNotFoundErrorResponseDto, InternalServerErrorResponseDto, InputValidationErrorResponseDto } from "@voyzu/types";
import { ItemCategoryChangeRequestDto, ItemCodeListRequestDto, ItemCreateRequestDto, ItemDeletionImpactDto, ItemListRowDto, ItemOptionsDto, ItemPatchRequestDto, ItemResponseDto, ItemSkuReservationDto } from "./types/item.types";

const skuPath = { sku: { description: "Organization-unique inventory item SKU.", schema: Type.String({ pattern: "^[A-Z0-9][A-Z0-9_-]*$" }) } };
const errors = {
  "400": { description: "Validation failed.", body: InputValidationErrorResponseDto },
  "404": { description: "The item was not found.", body: EntityNotFoundErrorResponseDto },
  "409": { description: "The request conflicts with existing data.", body: ConflictErrorResponseDto },
  "422": { description: "A business rule blocked the operation.", body: BusinessRuleErrorResponseDto },
  "500": { description: "An unexpected server error occurred.", body: InternalServerErrorResponseDto },
} as const;

export const httpApiRoutes = {
  "inventory.items.list": { description: "Lists inventory items for the selected organization. Free-text search includes all custom-field values.", method: "GET", path: "/inventory/items", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleList), summary: "List inventory items",   request: { query: { parameters: { q: { description: "Optional free-text search across item and custom-field values.", required: false } }, schema: Type.Object({ q: Type.Optional(Type.String()) }) } }, responses: { "200": { description: "Inventory items.", body: Type.Array(ItemListRowDto) }, ...errors } },
  "inventory.items.options": { description: "Returns categories for item forms.", method: "GET", path: "/inventory/items/options", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleOptions), summary: "Get item form options",   responses: { "200": { description: "Item categories.", body: ItemOptionsDto }, ...errors } },
  "inventory.items.reserveSku": { description: "Reserves the next item identity and returns its SKU.", method: "POST", path: "/inventory/items/reserve-sku", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleReserveSku), summary: "Reserve an automatic item SKU",   responses: { "200": { description: "Reserved item identity and SKU.", body: ItemSkuReservationDto }, ...errors } },
  "inventory.items.create": { description: "Creates an inventory item in the selected organization.", method: "POST", path: "/inventory/items", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleCreate), summary: "Create inventory item",   request: { contentType: "application/json", body: ItemCreateRequestDto }, responses: { "201": { description: "The created item.", body: ItemResponseDto }, ...errors } },
  "inventory.items.get": { description: "Gets an inventory item by SKU in the selected organization.", method: "GET", path: "/inventory/items/[sku]", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleGet), summary: "Get inventory item",   request: { path: skuPath }, responses: { "200": { description: "The inventory item.", body: ItemResponseDto }, ...errors } },
  "inventory.items.patch": { description: "Updates writable item details.", method: "PATCH", path: "/inventory/items/[sku]", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handlePatch), summary: "Patch inventory item",   request: { path: skuPath, contentType: "application/json", body: ItemPatchRequestDto }, responses: { "200": { description: "The updated item.", body: ItemResponseDto }, ...errors } },
  "inventory.items.delete": { description: "Deletes an item only when it has no units in stock.", method: "DELETE", path: "/inventory/items/[sku]", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleDelete), summary: "Delete inventory item",   request: { path: skuPath }, responses: { "204": { description: "Item deleted." }, ...errors } },
  "inventory.items.activate": { description: "Changes an inventory item to active status.", method: "POST", path: "/inventory/items/[sku]/activate", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleActivate), summary: "Activate inventory item",   request: { path: skuPath }, responses: { "200": { description: "The activated item.", body: ItemResponseDto }, ...errors } },
  "inventory.items.deactivate": { description: "Changes an inventory item to inactive status.", method: "POST", path: "/inventory/items/[sku]/deactivate", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleDeactivate), summary: "Deactivate inventory item",   request: { path: skuPath }, responses: { "200": { description: "The deactivated item.", body: ItemResponseDto }, ...errors } },
  "inventory.items.batchActivate": { description: "Activates the supplied inventory item SKUs.", method: "POST", path: "/inventory/items/batch/activate", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleBatchActivate), summary: "Activate inventory items",   request: { contentType: "application/json", body: ItemCodeListRequestDto }, responses: { "200": { description: "Activated items.", body: Type.Array(ItemResponseDto) }, ...errors } },
  "inventory.items.batchDeactivate": { description: "Deactivates the supplied inventory item SKUs.", method: "POST", path: "/inventory/items/batch/deactivate", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleBatchDeactivate), summary: "Deactivate inventory items",   request: { contentType: "application/json", body: ItemCodeListRequestDto }, responses: { "200": { description: "Deactivated items.", body: Type.Array(ItemResponseDto) }, ...errors } },
  "inventory.items.batchChangeCategory": { description: "Assigns the supplied inventory items to an active category.", method: "POST", path: "/inventory/items/batch/change-category", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleBatchChangeCategory), summary: "Change inventory item category",   request: { contentType: "application/json", body: ItemCategoryChangeRequestDto }, responses: { "200": { description: "Updated items.", body: Type.Array(ItemResponseDto) }, ...errors } },
  "inventory.items.deletionImpact": { description: "Lists items that cannot be deleted because they have positive stock on hand.", method: "POST", path: "/inventory/items/batch/deletion-impact", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleDeletionImpact), summary: "Validate inventory item deletion",   request: { contentType: "application/json", body: ItemCodeListRequestDto }, responses: { "200": { description: "Items blocked from deletion by stock on hand.", body: Type.Array(ItemDeletionImpactDto) }, ...errors } },
  "inventory.items.batchDelete": { description: "Deletes supplied items only when none has units in stock.", method: "POST", path: "/inventory/items/batch/delete", loadHandler: () => import("./server/http-api/item.http.handlers").then((module) => module.handleBatchDelete), summary: "Delete inventory items",   request: { contentType: "application/json", body: ItemCodeListRequestDto }, responses: { "204": { description: "Items deleted." }, ...errors } },
} as const;
