-- @voyzu/inventory database objects.
-- Audit fields follow the standard Voyzu audited-table contract.

CREATE TYPE inventory_reason_code AS ENUM (
  'STOCK_VARIANCE', 'DAMAGED', 'MISSING', 'FOUND', 'DATA_CORRECTION',
  'SALE', 'INTERNAL_CONSUMPTION', 'WRITE_OFF_DAMAGED', 'WRITE_OFF_OTHER',
  'SUPPLIER_RETURN', 'SAMPLE', 'PURCHASE', 'CUSTOMER_RETURN',
  'OPENING_STOCK', 'PRODUCTION', 'OTHER'
);

CREATE TABLE item_category (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    code                     business_code NOT NULL,
    name                     display_name NOT NULL,
    description              description_text NOT NULL DEFAULT '',
    status                   active_status NOT NULL DEFAULT 'ACTIVE',

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_item_category_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_item_category_organization_code UNIQUE (organization_id, code),
    CONSTRAINT uq_item_category_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_item_category_inventory_code CHECK (code LIKE 'INV-%')
);

CREATE TABLE item (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    sku                      business_code,
    name                     display_name NOT NULL,
    description              description_text NOT NULL DEFAULT '',
    item_category_id         BIGINT,
    unit                     TEXT,
    dimension_unit           TEXT,
    dimension_height         NUMERIC(18, 6),
    dimension_width          NUMERIC(18, 6),
    dimension_depth          NUMERIC(18, 6),
    weight_unit              TEXT,
    weight                   NUMERIC(18, 6),
    quantity_tracked         BOOLEAN NOT NULL DEFAULT TRUE,
    status                   active_status NOT NULL DEFAULT 'ACTIVE',

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_item_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_category_scope
      FOREIGN KEY (organization_id, item_category_id)
      REFERENCES item_category(organization_id, id),
    CONSTRAINT uq_item_organization_sku UNIQUE (organization_id, sku),
    CONSTRAINT uq_item_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_item_name
      CHECK (btrim(name) <> ''),
    CONSTRAINT ck_item_unit
      CHECK ((quantity_tracked AND unit IS NOT NULL AND btrim(unit) <> '' AND length(unit) <= 40)
          OR (NOT quantity_tracked AND unit IS NULL)),
    CONSTRAINT ck_item_dimension_unit
      CHECK (dimension_unit IS NULL OR dimension_unit IN ('mm', 'cm', 'm', 'in', 'ft')),
    CONSTRAINT ck_item_dimensions
      CHECK ((dimension_height IS NULL OR dimension_height > 0)
         AND (dimension_width IS NULL OR dimension_width > 0)
         AND (dimension_depth IS NULL OR dimension_depth > 0)),
    CONSTRAINT ck_item_weight_unit
      CHECK (weight_unit IS NULL OR weight_unit IN ('mg', 'g', 'kg', 'oz', 'lb')),
    CONSTRAINT ck_item_weight CHECK (weight IS NULL OR weight > 0)
);

CREATE TABLE warehouse (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    code                     business_code NOT NULL,
    name                     display_name NOT NULL,
    address_line_1           TEXT NOT NULL DEFAULT '',
    address_line_2           TEXT NOT NULL DEFAULT '',
    city                     TEXT NOT NULL DEFAULT '',
    region                   TEXT NOT NULL DEFAULT '',
    postcode                 TEXT NOT NULL DEFAULT '',
    country_code             TEXT,
    status                   active_status NOT NULL DEFAULT 'ACTIVE',

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_warehouse_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_warehouse_organization_code UNIQUE (organization_id, code),
    CONSTRAINT uq_warehouse_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_warehouse_inventory_code CHECK (code LIKE 'INV-%'),
    CONSTRAINT ck_warehouse_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_warehouse_country_code
      CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$')
);

CREATE TABLE inventory_transaction (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    code                     business_code NOT NULL,
    transaction_type         TEXT NOT NULL,
    transaction_date         TIMESTAMPTZ NOT NULL,
    source_type              TEXT NOT NULL DEFAULT 'DIRECT',
    source_id                BIGINT,
    reference                TEXT,
    notes                    TEXT NOT NULL DEFAULT '',

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_inventory_transaction_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_inventory_transaction_organization_code UNIQUE (organization_id, code),
    CONSTRAINT uq_inventory_transaction_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_inventory_transaction_code CHECK (code LIKE 'INV-%'),
    CONSTRAINT ck_inventory_transaction_type
      CHECK (transaction_type IN ('RECEIPT', 'ISSUE', 'TRANSFER', 'ADJUSTMENT')),
    CONSTRAINT ck_inventory_transaction_source_type
      CHECK (source_type IN ('DIRECT', 'STOCK_COUNT')),
    CONSTRAINT ck_inventory_transaction_source_link
      CHECK ((source_type = 'DIRECT' AND source_id IS NULL)
          OR (source_type = 'STOCK_COUNT' AND source_id IS NOT NULL))
);

CREATE TABLE inventory_transaction_line (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    inventory_transaction_id BIGINT NOT NULL,
    item_id                  BIGINT NOT NULL,
    item_code                business_code NOT NULL,
    item_name                TEXT NOT NULL,
    warehouse_id             BIGINT NOT NULL,
    quantity_change          NUMERIC(18, 4) NOT NULL,
    reason_code              inventory_reason_code,

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_inventory_transaction_line_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_transaction_line_header_scope
      FOREIGN KEY (organization_id, inventory_transaction_id)
      REFERENCES inventory_transaction(organization_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_transaction_line_warehouse_scope
      FOREIGN KEY (organization_id, warehouse_id) REFERENCES warehouse(organization_id, id),
    CONSTRAINT uq_inventory_transaction_line_organization_id
      UNIQUE (organization_id, id),
    CONSTRAINT ck_inventory_transaction_line_quantity CHECK (quantity_change <> 0)
);

-- Inventory records financial significance only. Classification, costing,
-- valuation, accounts, and journals remain the responsibility of Finance or
-- another consuming package.
CREATE TABLE inventory_financial_activity (
    id                            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id               BIGINT NOT NULL,
    inventory_transaction_line_id BIGINT NOT NULL,
    movement_type                 TEXT NOT NULL,
    reason_code                   inventory_reason_code NOT NULL,
    status                        TEXT NOT NULL DEFAULT 'AVAILABLE',

    creation_date                 audit_timestamp,
    creation_actor_type           actor_type,
    creation_user_id              TEXT,
    creation_mutation_id          UUID,
    updated_date                  audit_timestamp,
    updated_actor_type            actor_type,
    updated_user_id               TEXT,
    updated_mutation_id           UUID,
    deletion_date                 audit_timestamp,
    deletion_actor_type           actor_type,
    deletion_user_id              TEXT,
    deletion_mutation_id          UUID,

    CONSTRAINT fk_inventory_financial_activity_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_financial_activity_transaction_line_scope
      FOREIGN KEY (organization_id, inventory_transaction_line_id)
      REFERENCES inventory_transaction_line(organization_id, id),
    CONSTRAINT uq_inventory_financial_activity_transaction_line
      UNIQUE (inventory_transaction_line_id),
    CONSTRAINT ck_inventory_financial_activity_movement_type
      CHECK (movement_type IN ('RECEIPT', 'ISSUE', 'ADJUSTMENT')),
    CONSTRAINT ck_inventory_financial_activity_status
      CHECK (status IN ('AVAILABLE', 'PROCESSED'))
);

CREATE TABLE inventory_reservation (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    code                     business_code NOT NULL,
    source_type              TEXT NOT NULL DEFAULT 'DIRECT',
    source_id                BIGINT,
    reference                TEXT,
    notes                    TEXT NOT NULL DEFAULT '',
    reserved_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_inventory_reservation_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_inventory_reservation_organization_code UNIQUE (organization_id, code),
    CONSTRAINT uq_inventory_reservation_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_inventory_reservation_code CHECK (code LIKE 'INV-%'),
    CONSTRAINT ck_inventory_reservation_source_type CHECK (source_type = 'DIRECT'),
    CONSTRAINT ck_inventory_reservation_source_link
      CHECK (source_type = 'DIRECT' AND source_id IS NULL)
);

CREATE TABLE inventory_reservation_line (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    inventory_reservation_id BIGINT NOT NULL,
    item_id                  BIGINT NOT NULL,
    item_code                business_code NOT NULL,
    item_name                TEXT NOT NULL,
    warehouse_id             BIGINT NOT NULL,
    quantity_change          NUMERIC(18, 4) NOT NULL,
    reason_code              inventory_reason_code NOT NULL,

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_inventory_reservation_line_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_reservation_line_header_scope
      FOREIGN KEY (organization_id, inventory_reservation_id)
      REFERENCES inventory_reservation(organization_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_reservation_line_warehouse_scope
      FOREIGN KEY (organization_id, warehouse_id) REFERENCES warehouse(organization_id, id),
    CONSTRAINT ck_inventory_reservation_line_quantity_change CHECK (quantity_change <> 0)
);

CREATE TABLE stock_count (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    code                     business_code NOT NULL,
    warehouse_id             BIGINT NOT NULL,
    count_date               DATE NOT NULL,
    status                   TEXT NOT NULL DEFAULT 'DRAFT',
    reference                TEXT NOT NULL DEFAULT '',
    notes                    TEXT NOT NULL DEFAULT '',
    completed_at             TIMESTAMPTZ,

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_stock_count_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_count_warehouse_scope
      FOREIGN KEY (organization_id, warehouse_id) REFERENCES warehouse(organization_id, id),
    CONSTRAINT uq_stock_count_organization_code UNIQUE (organization_id, code),
    CONSTRAINT ck_stock_count_inventory_code CHECK (code LIKE 'INV-%'),
    CONSTRAINT uq_stock_count_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_stock_count_status
      CHECK (status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_stock_count_completion
      CHECK ((status = 'COMPLETED' AND completed_at IS NOT NULL) OR status <> 'COMPLETED')
);

CREATE TABLE stock_count_line (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    stock_count_id           BIGINT NOT NULL,
    item_id                  BIGINT NOT NULL,
    expected_quantity        NUMERIC(18, 4) NOT NULL,
    counted_quantity         NUMERIC(18, 4),
    reason_code              inventory_reason_code NOT NULL,

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_stock_count_line_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_count_line_header_scope
      FOREIGN KEY (organization_id, stock_count_id)
      REFERENCES stock_count(organization_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_count_line_item_scope
      FOREIGN KEY (organization_id, item_id) REFERENCES item(organization_id, id),
    CONSTRAINT uq_stock_count_line UNIQUE (organization_id, stock_count_id, item_id),
    CONSTRAINT ck_stock_count_line_expected CHECK (expected_quantity >= 0),
    CONSTRAINT ck_stock_count_line_counted CHECK (counted_quantity IS NULL OR counted_quantity >= 0)
);

CREATE TABLE inv_option_list (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    name                     display_name NOT NULL,
    is_shared                BOOLEAN NOT NULL DEFAULT TRUE,
    status                   active_status NOT NULL DEFAULT 'ACTIVE',

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_option_list_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_option_list_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_option_list_name CHECK (btrim(name) <> '')
);

CREATE TABLE inv_option_list_value (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    option_list_id           BIGINT NOT NULL,
    value                    TEXT NOT NULL,
    sort_order               INTEGER NOT NULL DEFAULT 0,
    status                   active_status NOT NULL DEFAULT 'ACTIVE',

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_option_list_value_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_option_list_value_list_scope
      FOREIGN KEY (organization_id, option_list_id)
      REFERENCES inv_option_list(organization_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_option_list_value UNIQUE (organization_id, option_list_id, value),
    CONSTRAINT uq_option_list_value_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_option_list_value_value CHECK (btrim(value) <> '')
);

CREATE TABLE inv_custom_field (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    name                     display_name NOT NULL,
    data_type                TEXT NOT NULL,
    applies_to               TEXT NOT NULL,
    required                 BOOLEAN NOT NULL DEFAULT FALSE,
    show_in_filter           BOOLEAN NOT NULL DEFAULT FALSE,
    option_list_id           BIGINT,
    status                   active_status NOT NULL DEFAULT 'ACTIVE',

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_custom_field_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_custom_field_option_list_scope
      FOREIGN KEY (organization_id, option_list_id) REFERENCES inv_option_list(organization_id, id),
    CONSTRAINT uq_custom_field_organization_id UNIQUE (organization_id, id),
    CONSTRAINT ck_custom_field_data_type
      CHECK (data_type IN ('TEXT', 'NUMBER', 'DATE', 'BOOLEAN', 'OPTION', 'MULTIPLE_OPTIONS')),
    CONSTRAINT ck_custom_field_applies_to
      CHECK (applies_to IN ('ITEM', 'RECEIPT', 'ISSUE')),
    CONSTRAINT ck_custom_field_show_in_filter
      CHECK (NOT show_in_filter OR
        (applies_to = 'ITEM' AND data_type IN ('BOOLEAN', 'OPTION', 'MULTIPLE_OPTIONS'))),
    CONSTRAINT ck_custom_field_options
      CHECK ((data_type IN ('OPTION', 'MULTIPLE_OPTIONS') AND option_list_id IS NOT NULL)
          OR (data_type NOT IN ('OPTION', 'MULTIPLE_OPTIONS') AND option_list_id IS NULL))
);

CREATE UNIQUE INDEX uq_inv_custom_field_organization_applies_to_name
  ON inv_custom_field (organization_id, applies_to, lower(btrim(name::text)));

CREATE TABLE inv_custom_field_value (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id          BIGINT NOT NULL,
    custom_field_id          BIGINT NOT NULL,
    record_id                BIGINT NOT NULL,
    text_value               TEXT,
    number_value             NUMERIC,
    date_value               DATE,
    boolean_value            BOOLEAN,
    option_list_value_id     BIGINT,

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id     UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id      UUID,
    deletion_date            audit_timestamp,
    deletion_actor_type      actor_type,
    deletion_user_id         TEXT,
    deletion_mutation_id     UUID,

    CONSTRAINT fk_custom_field_value_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_custom_field_value_field_scope
      FOREIGN KEY (organization_id, custom_field_id)
      REFERENCES inv_custom_field(organization_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_custom_field_value_option_scope
      FOREIGN KEY (organization_id, option_list_value_id)
      REFERENCES inv_option_list_value(organization_id, id),
    CONSTRAINT ck_custom_field_value_one_value
      CHECK (num_nonnulls(text_value, number_value, date_value, boolean_value, option_list_value_id) = 1)
);

CREATE TRIGGER item_category_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON item_category
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER item_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON item
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory', 'sku');

CREATE TRIGGER warehouse_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON warehouse
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inventory_transaction_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inventory_transaction
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inventory_transaction_line_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inventory_transaction_line
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inventory_financial_activity_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inventory_financial_activity
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inventory_reservation_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inventory_reservation
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inventory_reservation_line_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inventory_reservation_line
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER stock_count_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON stock_count
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER stock_count_line_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON stock_count_line
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inv_option_list_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inv_option_list
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inv_option_list_value_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inv_option_list_value
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inv_custom_field_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inv_custom_field
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');

CREATE TRIGGER inv_custom_field_value_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON inv_custom_field_value
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/inventory');
