CREATE TABLE IF NOT EXISTS ar_counterparty (
 id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
 organization_id BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
 party_id BIGINT NOT NULL REFERENCES party(id),
 status active_status,
 country_code iso_country_code REFERENCES country(code),
 tax_region_or_province TEXT,
 creation_date audit_timestamp, creation_actor_type actor_type, creation_user_id TEXT, creation_mutation_id UUID,
 updated_date audit_timestamp, updated_actor_type actor_type, updated_user_id TEXT, updated_mutation_id UUID,
 UNIQUE (organization_id, party_id)
);
CREATE TABLE IF NOT EXISTS ap_counterparty (
 id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
 organization_id BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
 party_id BIGINT NOT NULL REFERENCES party(id),
 status active_status,
 country_code iso_country_code REFERENCES country(code),
 tax_region_or_province TEXT,
 creation_date audit_timestamp, creation_actor_type actor_type, creation_user_id TEXT, creation_mutation_id UUID,
 updated_date audit_timestamp, updated_actor_type actor_type, updated_user_id TEXT, updated_mutation_id UUID,
 UNIQUE (organization_id, party_id)
);
CREATE TABLE IF NOT EXISTS finance_document (
 id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
 organization_id BIGINT NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
 document_type TEXT NOT NULL, code TEXT NOT NULL,
 document JSONB NOT NULL, details JSONB NOT NULL,
 UNIQUE (organization_id, document_type, code)
);

DROP TRIGGER IF EXISTS ar_counterparty_audit_trigger ON ar_counterparty;
CREATE TRIGGER ar_counterparty_audit_trigger
  BEFORE INSERT OR UPDATE OR DELETE ON ar_counterparty
  FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/finance');

DROP TRIGGER IF EXISTS ap_counterparty_audit_trigger ON ap_counterparty;
CREATE TRIGGER ap_counterparty_audit_trigger
  BEFORE INSERT OR UPDATE OR DELETE ON ap_counterparty
  FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/finance');
