-- ============================================================
-- Trial Balance Snapshot
-- Business domain: Company Accounting > Reporting
-- ============================================================

CREATE TABLE IF NOT EXISTS trial_balance_snapshot (
    id                          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_company_id                  BIGINT NOT NULL,
    as_at_date                  DATE NOT NULL,
    basis                       TEXT NOT NULL DEFAULT 'POSTED' CHECK (basis IN ('POSTED')),

    max_journal_header_id       BIGINT NOT NULL DEFAULT 0 CHECK (max_journal_header_id >= 0),
    journal_count               INTEGER NOT NULL DEFAULT 0 CHECK (journal_count >= 0),
    built_at                    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    gl_account_id               BIGINT NOT NULL,
    gl_account_code             business_code,
    gl_account_name             display_name NOT NULL,
    account_type                account_type NOT NULL,

    account_category_id         BIGINT,
    account_category_code       TEXT CHECK (account_category_code IS NULL OR account_category_code ~ '^[A-Z0-9_-]{1,40}$'),
    account_category_name       display_name,
    account_category_sequence   INTEGER CHECK (account_category_sequence IS NULL OR account_category_sequence >= 1),

    debit_amount                NUMERIC(18,2) NOT NULL DEFAULT 0,
    credit_amount               NUMERIC(18,2) NOT NULL DEFAULT 0,
    balance_amount              NUMERIC(18,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_trial_balance_snapshot_company
        FOREIGN KEY (finance_company_id)
        REFERENCES finance_company(id) ON DELETE CASCADE,

    CONSTRAINT fk_trial_balance_snapshot_gl_account
        FOREIGN KEY (gl_account_id)
        REFERENCES gl_account(id),

    CONSTRAINT fk_trial_balance_snapshot_account_category
        FOREIGN KEY (account_category_id)
        REFERENCES gl_account_category(id),

    CONSTRAINT uq_trial_balance_snapshot_account
        UNIQUE (finance_company_id, as_at_date, basis, gl_account_id)
);

CREATE INDEX IF NOT EXISTS idx_trial_balance_snapshot_report
    ON trial_balance_snapshot (finance_company_id, as_at_date, basis);

CREATE INDEX IF NOT EXISTS idx_trial_balance_snapshot_account_type
    ON trial_balance_snapshot (finance_company_id, as_at_date, basis, account_type);
