-- ============================================================
-- Bank / Cash Control Account
-- Business domain: Company Financial Settings > Bank / Cash Accounts
-- ============================================================

CREATE TABLE IF NOT EXISTS bank_cash_control_account (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_company_id               BIGINT NOT NULL,
    code                     business_code NOT NULL,
    ledger                   TEXT NOT NULL CHECK (ledger = 'BANK_CASH'),
    type                     bank_cash_account_type NOT NULL,
    gl_account_id            BIGINT NOT NULL,
    bank_name                display_name,
    bank_branch_name         display_name,
    bank_account_identifier  TEXT CHECK (
        bank_account_identifier IS NULL
        OR (
            length(bank_account_identifier) <= 100
            AND bank_account_identifier = btrim(bank_account_identifier)
        )
    ),
    cash_account_identifier  TEXT CHECK (
        cash_account_identifier IS NULL
        OR (
            length(cash_account_identifier) <= 100
            AND cash_account_identifier = btrim(cash_account_identifier)
        )
    ),
    status                   active_status,

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id UUID,
    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_bank_cash_control_account_company FOREIGN KEY (finance_company_id) REFERENCES finance_company(id),
    CONSTRAINT fk_bank_cash_control_account_gl_account FOREIGN KEY (finance_company_id, gl_account_id) REFERENCES gl_account(finance_company_id, id),
    CONSTRAINT uq_bank_cash_control_account_company_code UNIQUE (finance_company_id, code),
    CONSTRAINT uq_bank_cash_control_account_finance_company_id UNIQUE (finance_company_id, id)
);
