CREATE TABLE IF NOT EXISTS gl_account_category (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_organization_id BIGINT NOT NULL,
    code business_code NOT NULL,
    name display_name NOT NULL,
    account_type account_type NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence >= 1),
    status active_status,

    creation_date audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id TEXT,
    creation_mutation_id UUID,

    updated_date audit_timestamp,
    updated_actor_type actor_type,
    updated_user_id TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_gl_account_category_company
        FOREIGN KEY (finance_organization_id)
        REFERENCES finance_organization(id) ON DELETE CASCADE,

    CONSTRAINT uq_gl_account_category_company_code UNIQUE (finance_organization_id, code),
    CONSTRAINT uq_gl_account_category_finance_organization_id UNIQUE (finance_organization_id, id)
);
