-- Finance-owned copy of Inventory financial activity.
--
-- Inventory creates its own inventory_financial_activity record whenever a
-- stock quantity movement is financially relevant. When Finance is installed,
-- Inventory calls an optional Finance command in the same transaction and
-- Finance durably records the received activity here.
--
-- This is an inbound integration/work table, not an inventory ledger. Inventory
-- remains authoritative for operational stock movement; Finance owns subsequent
-- matching, document generation, posting, reversal, and exception handling.

CREATE TABLE IF NOT EXISTS finance_inventory_activity (
    id                              BIGINT PRIMARY KEY
                                    GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),

    finance_organization_id         BIGINT NOT NULL,

    -- Polymorphic source references into the optional Inventory package.
    -- These deliberately have no database foreign keys to Inventory tables.
    inventory_financial_activity_id BIGINT NOT NULL,
    inventory_transaction_line_id   BIGINT NOT NULL,

    -- Snapshot of the Inventory document which produced the activity.
    -- Examples: STOCK-ISS-10041, STOCK-REC-10023, STOCK-ADJ-10040.
    inventory_document_code         business_code NOT NULL,
    inventory_document_type         TEXT NOT NULL,

    -- Snapshot of the Inventory item identity.
    item_id                         BIGINT NOT NULL,
    item_code                       business_code NOT NULL,
    item_name                       TEXT NOT NULL,

    -- Positive quantities enter inventory; negative quantities leave it.
    quantity_change                 NUMERIC(18, 4) NOT NULL,
    reason_code                     TEXT,

    -- Operational activity timestamp supplied by Inventory.
    activity_date                   TIMESTAMPTZ NOT NULL,

    -- Finance-side integration processing state.
    processing_status               TEXT NOT NULL DEFAULT 'RECEIVED',

    -- Optional polymorphic reference to the Finance document which resolves
    -- this activity. All three fields must be populated together.
    finance_document_type           TEXT,
    finance_document_id             BIGINT,
    finance_document_code           business_code,
    processed_at                    TIMESTAMPTZ,

    creation_date                   audit_timestamp,
    creation_actor_type             actor_type,
    creation_user_id                TEXT,
    creation_mutation_id            UUID,
    updated_date                    audit_timestamp,
    updated_actor_type              actor_type,
    updated_user_id                 TEXT,
    updated_mutation_id             UUID,
    deletion_date                   audit_timestamp,
    deletion_actor_type             actor_type,
    deletion_user_id                TEXT,
    deletion_mutation_id            UUID,

    CONSTRAINT fk_finance_inventory_activity_finance_organization
      FOREIGN KEY (finance_organization_id)
      REFERENCES finance_organization(id)
      ON DELETE CASCADE,

    CONSTRAINT uq_finance_inventory_activity_source
      UNIQUE (
        finance_organization_id,
        inventory_financial_activity_id
      ),

    CONSTRAINT ck_finance_inventory_activity_quantity
      CHECK (quantity_change <> 0),

    CONSTRAINT ck_finance_inventory_activity_document_type
      CHECK (
        inventory_document_type IN (
          'RECEIPT',
          'ISSUE',
          'ADJUSTMENT'
        )
      ),

    CONSTRAINT ck_finance_inventory_activity_processing_status
      CHECK (
        processing_status IN (
          'RECEIVED',
          'PROCESSED',
          'ERROR'
        )
      ),

    CONSTRAINT ck_finance_inventory_activity_finance_document
      CHECK (
        (
          finance_document_type IS NULL
          AND finance_document_id IS NULL
          AND finance_document_code IS NULL
        )
        OR
        (
          finance_document_type IS NOT NULL
          AND finance_document_id IS NOT NULL
          AND finance_document_code IS NOT NULL
        )
      ),

    CONSTRAINT ck_finance_inventory_activity_processed_at
      CHECK (
        processing_status <> 'PROCESSED'
        OR processed_at IS NOT NULL
      )
);
