CREATE TABLE IF NOT EXISTS ar_counterparty (
    id                       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_organization_id               BIGINT NOT NULL,
    code                     business_code,
    name                     display_name NOT NULL,
    status                   active_status,
    country_code             iso_country_code,
    tax_region_or_province   TEXT,

    creation_date            audit_timestamp,
    creation_actor_type      actor_type,
    creation_user_id         TEXT,
    creation_mutation_id UUID,

    updated_date             audit_timestamp,
    updated_actor_type       actor_type,
    updated_user_id          TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_company    FOREIGN KEY (finance_organization_id) REFERENCES finance_organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_country    FOREIGN KEY (country_code) REFERENCES country(code),
    CONSTRAINT uq_ar_counterparty_company_code UNIQUE (finance_organization_id, code)
);

CREATE OR REPLACE FUNCTION trg_ar_counterparty_validate_region()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.tax_region_or_province IS NOT NULL THEN
        IF NEW.country_code IS NULL THEN
            RAISE EXCEPTION 'country_code is required when tax_region_or_province is supplied';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM tax_rule
            WHERE country_code = NEW.country_code
              AND region_code  = NEW.tax_region_or_province
              AND status       = 'ACTIVE'
        ) THEN
            RAISE EXCEPTION 'tax_region_or_province "%" is not a valid region for country "%"',
                NEW.tax_region_or_province, NEW.country_code;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ar_counterparty_region ON ar_counterparty;
CREATE TRIGGER trg_ar_counterparty_region
BEFORE INSERT OR UPDATE ON ar_counterparty
FOR EACH ROW EXECUTE FUNCTION trg_ar_counterparty_validate_region();
