CREATE TABLE IF NOT EXISTS posting_batch (
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code                TEXT NOT NULL DEFAULT '',
    finance_company_id          BIGINT NOT NULL,
    source_type         TEXT NOT NULL,
    doc_type            TEXT NOT NULL,
    doc_ref             TEXT NOT NULL,
    doc                 jsonb_object NOT NULL DEFAULT '{}'::jsonb,
    status              TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'POSTED', 'FAILED')),

    creation_date       audit_timestamp,
    creation_actor_type actor_type,
    updated_date        audit_timestamp,
    updated_actor_type  actor_type,

    CONSTRAINT fk_posting_batch_company FOREIGN KEY (finance_company_id) REFERENCES finance_company(id) ON DELETE CASCADE
);
