-- ============================================================
-- Dimension Value
-- Business domain: Company Financial Settings > Dimensions
-- ============================================================

CREATE TABLE IF NOT EXISTS dimension_value (
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_company_id            BIGINT NOT NULL,
    dimension_id          BIGINT NOT NULL,
    name                  TEXT NOT NULL,
    status                active_status,

    CONSTRAINT dimension_value_name_len   CHECK (length(name) BETWEEN 1 AND 14),
    CONSTRAINT dimension_value_name_trim  CHECK (name = btrim(name)),
    CONSTRAINT dimension_value_name_chars CHECK (name ~ '^[A-Za-z0-9 _-]+$'),
    CONSTRAINT fk_dimension_value_company FOREIGN KEY (finance_company_id) REFERENCES finance_company(id) ON DELETE CASCADE,
    CONSTRAINT fk_dimension_value_dimension FOREIGN KEY (finance_company_id, dimension_id) REFERENCES dimension(finance_company_id, id) ON DELETE CASCADE,
    CONSTRAINT dimension_value_dimension_id_id_unique UNIQUE (finance_company_id, dimension_id, id),
    CONSTRAINT dimension_value_legacy_dimension_id_unique UNIQUE (dimension_id, id),

    creation_date         audit_timestamp,
    creation_actor_type   actor_type,
    creation_user_id      TEXT,
    creation_mutation_id UUID,
    updated_date          audit_timestamp,
    updated_actor_type    actor_type,
    updated_user_id       TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID
);

CREATE UNIQUE INDEX IF NOT EXISTS dimension_value_name_unique
    ON dimension_value (finance_company_id, dimension_id, lower(name));
