CREATE TABLE IF NOT EXISTS finance_company (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    company_id BIGINT UNIQUE REFERENCES company(id),
    report_line_1 description_text,
    report_line_2 description_text,
    report_footer description_text,
    tax_filing_anchor_month INTEGER NOT NULL DEFAULT 3 CHECK (tax_filing_anchor_month BETWEEN 1 AND 12),
    tax_filing_interval_months INTEGER NOT NULL DEFAULT 3 CHECK (tax_filing_interval_months IN (1, 2, 3, 6, 12)),
    use_finance_template_settings BOOLEAN NOT NULL DEFAULT TRUE,
    is_template BOOLEAN NOT NULL DEFAULT FALSE,

    creation_date audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id TEXT,
    creation_mutation_id UUID,
    updated_date audit_timestamp,
    updated_actor_type actor_type,
    updated_user_id TEXT,
    updated_mutation_id UUID,
    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT finance_company_template_link_check CHECK (
      (is_template = TRUE AND company_id IS NULL)
      OR
      (is_template = FALSE AND company_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS finance_company_single_template
  ON finance_company (is_template)
  WHERE is_template = TRUE;
