CREATE TABLE IF NOT EXISTS gl_account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_company_id BIGINT NOT NULL,
    code business_code NOT NULL CHECK (length(code) <= 14),
    name display_name NOT NULL,
    account_type account_type NOT NULL,
    account_category_id BIGINT,
    status active_status,

    creation_date audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id TEXT,
    creation_mutation_id UUID,

    updated_date audit_timestamp,
    updated_actor_type actor_type,
    updated_user_id TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_gl_account_company
        FOREIGN KEY (finance_company_id)
        REFERENCES finance_company(id) ON DELETE CASCADE,

    CONSTRAINT fk_account_category
        FOREIGN KEY (finance_company_id, account_category_id)
        REFERENCES gl_account_category(finance_company_id, id),

    CONSTRAINT uq_gl_account_company_code UNIQUE (finance_company_id, code),
    CONSTRAINT uq_gl_account_finance_company_id UNIQUE (finance_company_id, id)
);
