import type { DbExecutor } from "@voyzu/capability/db";
import type { CreationAuditStamp } from "../../../common/server";
import type { FinanceCompanyResponseDto, FinanceCompanyUpdateRequestDto } from "@voyzu/finance/types/modules/finance-companies";

export interface FinanceCompanyRow {
  id: number; code: string; name: string; country_code: string; country_name: string; base_currency_code: string; currency_name: string; status: FinanceCompanyResponseDto["status"];
  creation_date: string; creation_actor_type: FinanceCompanyResponseDto["audit"]["created"]["actorType"]; creation_user_id: string | null; creation_mutation_id: string | null;
  updated_date: string; updated_actor_type: FinanceCompanyResponseDto["audit"]["updated"]["actorType"]; updated_user_id: string | null; updated_mutation_id: string | null;
  finance_organization_id: number | null; tax_filing_anchor_month: number; tax_filing_interval_months: 1 | 2 | 3 | 6 | 12;
  use_finance_template_settings: boolean; report_line_1: string | null; report_line_2: string | null; report_footer: string | null; has_postings: boolean;
}

const SELECT_SQL = `SELECT c.id::int, c.code, c.name, c.country_code, country.name AS country_name, c.base_currency_code, currency.name AS currency_name, c.status, c.creation_date, c.creation_actor_type, c.creation_user_id, c.creation_mutation_id, c.updated_date, c.updated_actor_type, c.updated_user_id, c.updated_mutation_id, fc.id::int AS finance_organization_id, COALESCE(fc.tax_filing_anchor_month, finance_country.tax_filing_anchor_month, 3)::int AS tax_filing_anchor_month, COALESCE(fc.tax_filing_interval_months, finance_country.tax_filing_interval_months, 3)::int AS tax_filing_interval_months, COALESCE(fc.use_finance_template_settings, true) AS use_finance_template_settings, fc.report_line_1, fc.report_line_2, fc.report_footer, EXISTS (SELECT 1 FROM journal_header j WHERE j.finance_organization_id = fc.id) AS has_postings FROM organization c JOIN country ON country.code = c.country_code JOIN currency ON currency.code = c.base_currency_code LEFT JOIN finance_country ON finance_country.code = c.country_code LEFT JOIN finance_organization fc ON fc.organization_id = c.id AND fc.is_template = false`;

export class FinanceCompanyRepo {
  constructor(private readonly db: DbExecutor) {}
  async getByCode(code: string): Promise<FinanceCompanyRow | null> { const { rows } = await this.db.query(`${SELECT_SQL} WHERE c.code = $1 AND c.status != 'DELETED'`, [code]); return (rows[0] as unknown as FinanceCompanyRow | undefined) ?? null; }
  async list(): Promise<FinanceCompanyRow[]> { const { rows } = await this.db.query(`${SELECT_SQL} WHERE c.status != 'DELETED' ORDER BY c.code`); return rows as unknown as FinanceCompanyRow[]; }
  async listOrganizationIds(): Promise<number[]> { const { rows } = await this.db.query(`SELECT organization_id::int FROM finance_organization WHERE is_template = false AND organization_id IS NOT NULL`); return rows.map((r) => Number(r.organization_id)); }
  lock(code: string): Promise<unknown> { return this.db.query("SELECT pg_advisory_xact_lock(hashtext($1))", [`voyzu.finance-company.${code}`]); }
  async getActivationContext(code: string): Promise<Record<string, unknown> | null> { const { rows } = await this.db.query(`SELECT c.id::int, c.status, fc.financial_period_start_month, fc.tax_filing_anchor_month::int, fc.tax_filing_interval_months::int FROM organization c LEFT JOIN finance_country fc ON fc.code = c.country_code WHERE c.code = $1 AND c.status != 'DELETED' FOR UPDATE OF c`, [code]); return (rows[0] as Record<string, unknown> | undefined) ?? null; }
  async ensureFinanceOrganization(organizationId: number, anchorMonth: unknown, intervalMonths: unknown): Promise<number | null> { const inserted = await this.db.query(`INSERT INTO finance_organization (organization_id, tax_filing_anchor_month, tax_filing_interval_months, use_finance_template_settings, is_template) VALUES ($1, $2, $3, true, false) ON CONFLICT (organization_id) DO NOTHING RETURNING id::int`, [organizationId, anchorMonth, intervalMonths]); if (inserted.rows[0]?.id != null) return Number(inserted.rows[0].id); const existing = await this.db.query("SELECT id::int FROM finance_organization WHERE organization_id = $1 AND is_template = false", [organizationId]); return existing.rows[0]?.id == null ? null : Number(existing.rows[0].id); }

  async createFiscalCalendar(financeCompanyId: number, startMonth: string, audit: CreationAuditStamp): Promise<void> {
    await this.db.query(`WITH settings AS (SELECT CASE $2 WHEN 'JAN' THEN 1 WHEN 'FEB' THEN 2 WHEN 'MAR' THEN 3 WHEN 'APR' THEN 4 WHEN 'MAY' THEN 5 WHEN 'JUN' THEN 6 WHEN 'JUL' THEN 7 WHEN 'AUG' THEN 8 WHEN 'SEP' THEN 9 WHEN 'OCT' THEN 10 WHEN 'NOV' THEN 11 WHEN 'DEC' THEN 12 ELSE 1 END AS start_month), years AS (SELECT generate_series(EXTRACT(YEAR FROM CURRENT_DATE)::int - 2, EXTRACT(YEAR FROM CURRENT_DATE)::int + 5) AS financial_year), proposed AS (SELECT years.financial_year, make_date(years.financial_year - CASE WHEN settings.start_month = 1 THEN 0 ELSE 1 END, settings.start_month, 1) AS start_date FROM years CROSS JOIN settings) INSERT INTO fiscal_year (finance_organization_id, code, name, start_date, end_date, status, creation_actor_type, creation_user_id, creation_mutation_id, updated_actor_type, updated_user_id, updated_mutation_id) SELECT $1, 'FY-' || financial_year, 'Financial Year ' || financial_year, start_date, (start_date + INTERVAL '1 year - 1 day')::date, CASE WHEN (start_date + INTERVAL '1 year - 1 day')::date < CURRENT_DATE THEN 'INACTIVE' WHEN start_date <= CURRENT_DATE THEN 'OPEN' ELSE 'PLANNED' END, $3, $4, $5::uuid, $3, $4, $5::uuid FROM proposed ON CONFLICT (finance_organization_id, code) DO NOTHING`, [financeCompanyId, startMonth, audit.actorType, audit.userId, audit.mutationId]);
    await this.db.query(`WITH proposed AS (SELECT fy.finance_organization_id, fy.id AS fiscal_year_id, month_start::date AS start_date, (month_start + INTERVAL '1 month - 1 day')::date AS end_date FROM fiscal_year fy CROSS JOIN LATERAL generate_series(date_trunc('month', fy.start_date::timestamp), date_trunc('month', fy.end_date::timestamp), INTERVAL '1 month') AS month_start WHERE fy.finance_organization_id = $1 AND fy.status = 'OPEN') INSERT INTO fiscal_period (finance_organization_id, fiscal_year_id, code, name, start_date, end_date, status, creation_actor_type, creation_user_id, creation_mutation_id, updated_actor_type, updated_user_id, updated_mutation_id) SELECT finance_organization_id, fiscal_year_id, upper(to_char(start_date, 'MON')), trim(to_char(start_date, 'Month')), start_date, end_date, 'OPEN', $2, $3, $4::uuid, $2, $3, $4::uuid FROM proposed ON CONFLICT (fiscal_year_id, code) DO NOTHING`, [financeCompanyId, audit.actorType, audit.userId, audit.mutationId]);
  }

  async updateSettings(id: number, input: FinanceCompanyUpdateRequestDto): Promise<void> { await this.db.query(`UPDATE finance_organization SET tax_filing_anchor_month = $2, tax_filing_interval_months = $3, use_finance_template_settings = $4, report_line_1 = NULLIF($5, ''), report_line_2 = NULLIF($6, ''), report_footer = NULLIF($7, '') WHERE id = $1`, [id, input.taxFilingAnchorMonth, input.taxFilingIntervalMonths, input.useFinanceTemplateSettings, input.reportLine1 ?? "", input.reportLine2 ?? "", input.reportFooter ?? ""]); }
  async deleteByOrganizationId(organizationId: number): Promise<void> { await this.db.query(`DELETE FROM finance_organization WHERE organization_id = $1 AND is_template = false`, [organizationId]); }

  async copyTemplateSettings(financeCompanyId: number): Promise<boolean> {
    const template = await this.db.query("SELECT id::int FROM finance_organization WHERE is_template = true ORDER BY id LIMIT 1");
    const templateId = template.rows[0]?.id == null ? null : Number(template.rows[0].id);
    if (!templateId) return false;
    const p = [financeCompanyId, templateId];
    await this.db.query(`INSERT INTO gl_account_category (finance_organization_id, code, name, account_type, sequence, status) SELECT $1, code, name, account_type, sequence, status FROM gl_account_category WHERE finance_organization_id = $2 AND status = 'ACTIVE' ON CONFLICT (finance_organization_id, code) DO NOTHING`, p);
    await this.db.query(`INSERT INTO gl_account (finance_organization_id, code, name, account_type, account_category_id, status) SELECT $1, source.code, source.name, source.account_type, target_category.id, source.status FROM gl_account source LEFT JOIN gl_account_category source_category ON source_category.finance_organization_id = source.finance_organization_id AND source_category.id = source.account_category_id LEFT JOIN gl_account_category target_category ON target_category.finance_organization_id = $1 AND target_category.code = source_category.code WHERE source.finance_organization_id = $2 AND source.status = 'ACTIVE' ON CONFLICT (finance_organization_id, code) DO NOTHING`, p);
    for (const table of ["ar_control_account", "ap_control_account"] as const) await this.db.query(`INSERT INTO ${table} (finance_organization_id, code, ledger, name, gl_account_id, status) SELECT $1, source.code, source.ledger, source.name, target_gl.id, source.status FROM ${table} source JOIN gl_account source_gl ON source_gl.finance_organization_id = source.finance_organization_id AND source_gl.id = source.gl_account_id JOIN gl_account target_gl ON target_gl.finance_organization_id = $1 AND target_gl.code = source_gl.code WHERE source.finance_organization_id = $2 AND source.status = 'ACTIVE' ON CONFLICT (finance_organization_id, code) DO NOTHING`, p);
    await this.copyControlTable("tax_control_account", "ledger, name, description, tax_family_code", "source.ledger, source.name, source.description, source.tax_family_code", p);
    await this.copyControlTable("inventory_control_account", "ledger, name, description", "source.ledger, source.name, source.description", p);
    await this.db.query(`INSERT INTO bank_cash_control_account (finance_organization_id, code, ledger, type, gl_account_id, bank_name, bank_branch_name, bank_account_identifier, cash_account_identifier, status) SELECT $1, source.code, source.ledger, source.type, target_gl.id, source.bank_name, source.bank_branch_name, source.bank_account_identifier, source.cash_account_identifier, source.status FROM bank_cash_control_account source JOIN gl_account source_gl ON source_gl.finance_organization_id = source.finance_organization_id AND source_gl.id = source.gl_account_id JOIN gl_account target_gl ON target_gl.finance_organization_id = $1 AND target_gl.code = source_gl.code WHERE source.finance_organization_id = $2 AND source.status = 'ACTIVE' ON CONFLICT (finance_organization_id, code) DO NOTHING`, p);
    await this.db.query(`INSERT INTO dimension (finance_organization_id, code, name, status) SELECT $1, code, name, status FROM dimension WHERE finance_organization_id = $2 AND status = 'ACTIVE' ON CONFLICT (finance_organization_id, code) DO NOTHING`, p);
    await this.db.query(`INSERT INTO dimension_value (finance_organization_id, dimension_id, name, status) SELECT $1, target_dimension.id, source_value.name, source_value.status FROM dimension_value source_value JOIN dimension source_dimension ON source_dimension.finance_organization_id = source_value.finance_organization_id AND source_dimension.id = source_value.dimension_id JOIN dimension target_dimension ON target_dimension.finance_organization_id = $1 AND target_dimension.code = source_dimension.code WHERE source_value.finance_organization_id = $2 AND source_value.status = 'ACTIVE' ON CONFLICT (finance_organization_id, dimension_id, lower(name)) DO NOTHING`, p);
    await this.db.query(`INSERT INTO financial_document_default (finance_organization_id, document_code, code, name, target_type, allowed_account_types, override_property_name, override_scope, gl_account_id, bank_cash_control_account_id, status) SELECT $1, source.document_code, source.code, source.name, source.target_type, source.allowed_account_types, source.override_property_name, source.override_scope, target_gl.id, target_bank.id, source.status FROM financial_document_default source LEFT JOIN gl_account source_gl ON source_gl.finance_organization_id = source.finance_organization_id AND source_gl.id = source.gl_account_id LEFT JOIN gl_account target_gl ON target_gl.finance_organization_id = $1 AND target_gl.code = source_gl.code LEFT JOIN bank_cash_control_account source_bank ON source_bank.finance_organization_id = source.finance_organization_id AND source_bank.id = source.bank_cash_control_account_id LEFT JOIN bank_cash_control_account target_bank ON target_bank.finance_organization_id = $1 AND target_bank.code = source_bank.code WHERE source.finance_organization_id = $2 AND source.status = 'ACTIVE' ON CONFLICT (finance_organization_id, document_code, code) DO NOTHING`, p);
    await this.db.query(`INSERT INTO item_posting_profile (finance_organization_id, code, name, description, is_sold, is_purchased, is_consumed, revenue_gl_account_id, cogs_gl_account_id, purchase_expense_gl_account_id, consumption_gl_account_id, adjustment_gain_gl_account_id, adjustment_loss_gl_account_id, status) SELECT $1, source.code, source.name, source.description, source.is_sold, source.is_purchased, source.is_consumed, revenue_target.id, cogs_target.id, purchase_target.id, consumption_target.id, gain_target.id, loss_target.id, source.status FROM item_posting_profile source LEFT JOIN gl_account revenue_source ON revenue_source.finance_organization_id = source.finance_organization_id AND revenue_source.id = source.revenue_gl_account_id LEFT JOIN gl_account revenue_target ON revenue_target.finance_organization_id = $1 AND revenue_target.code = revenue_source.code LEFT JOIN gl_account cogs_source ON cogs_source.finance_organization_id = source.finance_organization_id AND cogs_source.id = source.cogs_gl_account_id LEFT JOIN gl_account cogs_target ON cogs_target.finance_organization_id = $1 AND cogs_target.code = cogs_source.code LEFT JOIN gl_account purchase_source ON purchase_source.finance_organization_id = source.finance_organization_id AND purchase_source.id = source.purchase_expense_gl_account_id LEFT JOIN gl_account purchase_target ON purchase_target.finance_organization_id = $1 AND purchase_target.code = purchase_source.code LEFT JOIN gl_account consumption_source ON consumption_source.finance_organization_id = source.finance_organization_id AND consumption_source.id = source.consumption_gl_account_id LEFT JOIN gl_account consumption_target ON consumption_target.finance_organization_id = $1 AND consumption_target.code = consumption_source.code LEFT JOIN gl_account gain_source ON gain_source.finance_organization_id = source.finance_organization_id AND gain_source.id = source.adjustment_gain_gl_account_id LEFT JOIN gl_account gain_target ON gain_target.finance_organization_id = $1 AND gain_target.code = gain_source.code LEFT JOIN gl_account loss_source ON loss_source.finance_organization_id = source.finance_organization_id AND loss_source.id = source.adjustment_loss_gl_account_id LEFT JOIN gl_account loss_target ON loss_target.finance_organization_id = $1 AND loss_target.code = loss_source.code WHERE source.finance_organization_id = $2 AND source.status = 'ACTIVE' ON CONFLICT (finance_organization_id, code) DO NOTHING`, p);
    return true;
  }

  private copyControlTable(table: "tax_control_account" | "inventory_control_account", columns: string, sourceColumns: string, params: number[]): Promise<unknown> { return this.db.query(`INSERT INTO ${table} (finance_organization_id, code, ${columns}, gl_account_id, status) SELECT $1, source.code, ${sourceColumns}, target_gl.id, source.status FROM ${table} source JOIN gl_account source_gl ON source_gl.finance_organization_id = source.finance_organization_id AND source_gl.id = source.gl_account_id JOIN gl_account target_gl ON target_gl.finance_organization_id = $1 AND target_gl.code = source_gl.code WHERE source.finance_organization_id = $2 AND source.status = 'ACTIVE' ON CONFLICT (finance_organization_id, code) DO NOTHING`, params); }
}
