-- Generic cross-package document lineage. Document identifiers are polymorphic
-- references resolved by application code; document codes are snapshots for
-- display when the owning package is unavailable.
CREATE TABLE IF NOT EXISTS document_link (
    id                         BIGINT PRIMARY KEY
                               GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    organization_id            BIGINT NOT NULL,
    upstream_document_type     TEXT NOT NULL,
    upstream_document_id       BIGINT NOT NULL,
    upstream_document_code     business_code NOT NULL,
    downstream_document_type   TEXT NOT NULL,
    downstream_document_id     BIGINT NOT NULL,
    downstream_document_code   business_code NOT NULL,

    creation_date               audit_timestamp,
    creation_actor_type         actor_type,
    creation_user_id            TEXT,
    creation_mutation_id        UUID,
    updated_date                audit_timestamp,
    updated_actor_type          actor_type,
    updated_user_id             TEXT,
    updated_mutation_id         UUID,
    deletion_date               audit_timestamp,
    deletion_actor_type         actor_type,
    deletion_user_id            TEXT,
    deletion_mutation_id        UUID,

    CONSTRAINT fk_document_link_organization
      FOREIGN KEY (organization_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_document_link
      UNIQUE (
        organization_id,
        upstream_document_type,
        upstream_document_id,
        downstream_document_type,
        downstream_document_id
      ),
    CONSTRAINT ck_document_link_upstream_type
      CHECK (btrim(upstream_document_type) <> ''),
    CONSTRAINT ck_document_link_downstream_type
      CHECK (btrim(downstream_document_type) <> ''),
    CONSTRAINT ck_document_link_not_self
      CHECK (
        upstream_document_type <> downstream_document_type
        OR upstream_document_id <> downstream_document_id
      )
);
