DO $$
BEGIN
  IF to_regclass('public.app_user_assignment') IS NOT NULL
     AND to_regclass('public.company_user_access') IS NULL THEN
    ALTER TABLE app_user_assignment RENAME TO company_user_access;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS company_user_access (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,

    creation_date audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id TEXT,
    creation_mutation_id UUID,

    updated_date audit_timestamp,
    updated_actor_type actor_type,
    updated_user_id TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT company_user_access_user_fk
      FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT company_user_access_company_fk
      FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE,
    CONSTRAINT company_user_access_unique UNIQUE (user_id, company_id)
);
