WITH seed (code, name, account_type, category_code, status) AS (
  VALUES
    ('100000', 'Bank – Operating Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('100100', 'Bank – Payroll Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('100200', 'Bank – Savings Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('100300', 'Bank Clearing / Settlement Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('100400', 'Undeposited Funds', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('101000', 'Cash on Hand', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('110000', 'Accounts Receivable – Trade', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('111000', 'Accounts Receivable – Unapplied Cash / Credits', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('112000', 'Allowance for Doubtful Debts', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('120000', 'Tax on Purchases - Recoverable', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('121000', 'Inventory Control', 'ASSET', 'ASSET_INVENTORY', 'ACTIVE'),
    ('121500', 'Inventory Receipt Clearing', 'ASSET', 'ASSET_INVENTORY', 'ACTIVE'),
    ('130000', 'Prepayments', 'ASSET', 'ASSET_PREPAYMENTS', 'ACTIVE'),
    ('131000', 'Deposits Paid', 'ASSET', 'ASSET_PREPAYMENTS', 'ACTIVE'),
    ('132000', 'Accrued Income', 'ASSET', 'ASSET_PREPAYMENTS', 'ACTIVE'),
    ('150000', 'Plant & Equipment – Cost', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('151000', 'Accumulated Depreciation – PPE', 'ASSET', 'ASSET_ACCUM_DEP', 'ACTIVE'),
    ('152000', 'Motor Vehicles – Cost', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('153000', 'Accumulated Depreciation – Vehicles', 'ASSET', 'ASSET_ACCUM_DEP', 'ACTIVE'),
    ('158000', 'Capital Work in Progress', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('159000', 'Asset Disposal Clearing', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('160000', 'Software – Cost', 'ASSET', 'ASSET_INTANGIBLE', 'ACTIVE'),
    ('161000', 'Accumulated Amortisation – Software', 'ASSET', 'ASSET_INTANGIBLE', 'ACTIVE'),
    ('200000', 'Accounts Payable – Trade', 'LIABILITY', 'LIABILITY_AP', 'ACTIVE'),
    ('201000', 'Accounts Payable – Unapplied Payments / Credits', 'LIABILITY', 'LIABILITY_AP', 'ACTIVE'),
    ('210000', 'GST / VAT Payable', 'LIABILITY', 'LIABILITY_GST', 'ACTIVE'),
    ('211000', 'GST / VAT Receivable', 'LIABILITY', 'LIABILITY_GST', 'ACTIVE'),
    ('220000', 'Tax on Sales - Payable', 'LIABILITY', 'LIABILITY_GST', 'ACTIVE'),
    ('222000', 'Payroll Liabilities – Super', 'LIABILITY', 'LIABILITY_PAYROLL', 'ACTIVE'),
    ('223000', 'Employer Contributions Payable', 'LIABILITY', 'LIABILITY_PAYROLL', 'ACTIVE'),
    ('230000', 'Deferred Revenue', 'LIABILITY', 'LIABILITY_DEFERRED', 'ACTIVE'),
    ('240000', 'Accrued Expenses', 'LIABILITY', 'LIABILITY_AP', 'ACTIVE'),
    ('250000', 'Bank Loans – Long Term', 'LIABILITY', 'LIABILITY_LOANS', 'ACTIVE'),
    ('251000', 'Lease Liabilities', 'LIABILITY', 'LIABILITY_LOANS', 'ACTIVE'),
    ('260000', 'Interest Payable', 'LIABILITY', 'LIABILITY_LOANS', 'ACTIVE'),
    ('300000', 'Opening Balance Equity', 'EQUITY', 'EQUITY_CAPITAL', 'ACTIVE'),
    ('310000', 'Retained Earnings', 'EQUITY', 'EQUITY_RETAINED', 'ACTIVE'),
    ('320000', 'Current Year Earnings', 'EQUITY', 'EQUITY_RETAINED', 'ACTIVE'),
    ('330000', 'Owner Drawings', 'EQUITY', 'EQUITY_DRAWINGS', 'ACTIVE'),
    ('340000', 'Dividends Payable', 'EQUITY', 'EQUITY_DRAWINGS', 'ACTIVE'),
    ('390000', 'Legacy Opening Balance Equity', 'EQUITY', 'EQUITY_RETAINED', 'ACTIVE'),
    ('400000', 'Sales  Products', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('401000', 'Sales - Events', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('402000', 'Sales  Subscriptions', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('403000', 'Consulting', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('405000', 'Inventory Adjustment Gain / Stock Gain', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('410000', 'Sales Discounts', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('450000', 'Other Income', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('451000', 'Interest Income', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('452000', 'Supplier Balances Written Off', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('500000', 'Cost of Goods Sold', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('501000', 'Cost of Goods Sold  Labour', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('502000', 'Freight Inwards', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('503000', 'Packaging and Fulfilment Supplies', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('504000', 'Raw Materials Consumed', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('505000', 'Inventory Adjustment Loss', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('506000', 'Samples and Demo Stock Consumed', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('600000', 'Wages and Salaries', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('601000', 'Payroll Taxes', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('602000', 'Superannuation Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('603000', 'Tax Adjustments', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('610000', 'Bad Debt Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('611000', 'Repairs and Maintenance', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('612000', 'Office Supplies', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('613000', 'Consumables Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('614000', 'Freight and Courier', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('620000', 'Utilities', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('630000', 'IT and Software', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('631000', 'Telecommunications', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('640000', 'Advertising', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('641000', 'Marketing & Promotions', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('650000', 'Professional Fees', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('651000', 'Accounting & Audit Fees', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('699000', 'General Expenses', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('700000', 'Depreciation – Plant & Equipment', 'EXPENSE', 'EXPENSE_DEPRECIATION', 'ACTIVE'),
    ('701000', 'Depreciation – Vehicles', 'EXPENSE', 'EXPENSE_DEPRECIATION', 'ACTIVE'),
    ('710000', 'Amortisation – Software', 'EXPENSE', 'EXPENSE_DEPRECIATION', 'ACTIVE'),
    ('800000', 'Interest Expense', 'EXPENSE', 'EXPENSE_INTEREST', 'ACTIVE'),
    ('810000', 'Bank Fees', 'EXPENSE', 'EXPENSE_INTEREST', 'ACTIVE'),
    ('820000', 'Doubtful Debt Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE')
)
INSERT INTO gl_account (finance_organization_id, code, name, account_type, account_category_id, status, creation_actor_type, updated_actor_type)
SELECT fc.id, s.code, s.name, s.account_type, cat.id, s.status, 'SYSTEM', 'SYSTEM'
FROM seed s
CROSS JOIN finance_organization fc
LEFT JOIN gl_account_category cat ON cat.finance_organization_id = fc.id AND cat.code = s.category_code
ON CONFLICT (finance_organization_id, code) DO UPDATE SET
  name = EXCLUDED.name,
  account_type = EXCLUDED.account_type,
  account_category_id = EXCLUDED.account_category_id,
  status = EXCLUDED.status,
  updated_date = NOW(),
  updated_actor_type = 'SYSTEM';
