WITH seed (company_code, code, name, account_type, category_code, status) AS (
  VALUES
    ('TEMPLATE', '100000', 'Bank – Operating Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('TEMPLATE', '100100', 'Bank – Payroll Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('TEMPLATE', '100200', 'Bank – Savings Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('TEMPLATE', '100300', 'Bank Clearing / Settlement Account', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('TEMPLATE', '100400', 'Undeposited Funds', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('TEMPLATE', '101000', 'Cash on Hand', 'ASSET', 'ASSET_BANK', 'ACTIVE'),
    ('TEMPLATE', '110000', 'Accounts Receivable – Trade', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('TEMPLATE', '111000', 'Accounts Receivable – Unapplied Cash / Credits', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('TEMPLATE', '112000', 'Allowance for Doubtful Debts', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('TEMPLATE', '120000', 'Tax on Purchases - Recoverable', 'ASSET', 'ASSET_ACCOUNTS_REC', 'ACTIVE'),
    ('TEMPLATE', '121000', 'Inventory Control', 'ASSET', 'ASSET_INVENTORY', 'ACTIVE'),
    ('TEMPLATE', '121500', 'Inventory Receipt Clearing', 'ASSET', 'ASSET_INVENTORY', 'ACTIVE'),
    ('TEMPLATE', '130000', 'Prepayments', 'ASSET', 'ASSET_PREPAYMENTS', 'ACTIVE'),
    ('TEMPLATE', '131000', 'Deposits Paid', 'ASSET', 'ASSET_PREPAYMENTS', 'ACTIVE'),
    ('TEMPLATE', '132000', 'Accrued Income', 'ASSET', 'ASSET_PREPAYMENTS', 'ACTIVE'),
    ('TEMPLATE', '150000', 'Plant & Equipment – Cost', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('TEMPLATE', '151000', 'Accumulated Depreciation – PPE', 'ASSET', 'ASSET_ACCUM_DEP', 'ACTIVE'),
    ('TEMPLATE', '152000', 'Motor Vehicles – Cost', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('TEMPLATE', '153000', 'Accumulated Depreciation – Vehicles', 'ASSET', 'ASSET_ACCUM_DEP', 'ACTIVE'),
    ('TEMPLATE', '158000', 'Capital Work in Progress', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('TEMPLATE', '159000', 'Asset Disposal Clearing', 'ASSET', 'ASSET_PPE', 'ACTIVE'),
    ('TEMPLATE', '160000', 'Software – Cost', 'ASSET', 'ASSET_INTANGIBLE', 'ACTIVE'),
    ('TEMPLATE', '161000', 'Accumulated Amortisation – Software', 'ASSET', 'ASSET_INTANGIBLE', 'ACTIVE'),
    ('TEMPLATE', '200000', 'Accounts Payable – Trade', 'LIABILITY', 'LIABILITY_AP', 'ACTIVE'),
    ('TEMPLATE', '201000', 'Accounts Payable – Unapplied Payments / Credits', 'LIABILITY', 'LIABILITY_AP', 'ACTIVE'),
    ('TEMPLATE', '210000', 'GST / VAT Payable', 'LIABILITY', 'LIABILITY_GST', 'ACTIVE'),
    ('TEMPLATE', '211000', 'GST / VAT Receivable', 'LIABILITY', 'LIABILITY_GST', 'ACTIVE'),
    ('TEMPLATE', '220000', 'Tax on Sales - Payable', 'LIABILITY', 'LIABILITY_GST', 'ACTIVE'),
    ('TEMPLATE', '222000', 'Payroll Liabilities – Super', 'LIABILITY', 'LIABILITY_PAYROLL', 'ACTIVE'),
    ('TEMPLATE', '223000', 'Employer Contributions Payable', 'LIABILITY', 'LIABILITY_PAYROLL', 'ACTIVE'),
    ('TEMPLATE', '230000', 'Deferred Revenue', 'LIABILITY', 'LIABILITY_DEFERRED', 'ACTIVE'),
    ('TEMPLATE', '240000', 'Accrued Expenses', 'LIABILITY', 'LIABILITY_AP', 'ACTIVE'),
    ('TEMPLATE', '250000', 'Bank Loans – Long Term', 'LIABILITY', 'LIABILITY_LOANS', 'ACTIVE'),
    ('TEMPLATE', '251000', 'Lease Liabilities', 'LIABILITY', 'LIABILITY_LOANS', 'ACTIVE'),
    ('TEMPLATE', '260000', 'Interest Payable', 'LIABILITY', 'LIABILITY_LOANS', 'ACTIVE'),
    ('TEMPLATE', '300000', 'Opening Balance Equity', 'EQUITY', 'EQUITY_CAPITAL', 'ACTIVE'),
    ('TEMPLATE', '310000', 'Retained Earnings', 'EQUITY', 'EQUITY_RETAINED', 'ACTIVE'),
    ('TEMPLATE', '320000', 'Current Year Earnings', 'EQUITY', 'EQUITY_RETAINED', 'ACTIVE'),
    ('TEMPLATE', '330000', 'Owner Drawings', 'EQUITY', 'EQUITY_DRAWINGS', 'ACTIVE'),
    ('TEMPLATE', '340000', 'Dividends Payable', 'EQUITY', 'EQUITY_DRAWINGS', 'ACTIVE'),
    ('TEMPLATE', '390000', 'Legacy Opening Balance Equity', 'EQUITY', 'EQUITY_RETAINED', 'ACTIVE'),
    ('TEMPLATE', '400000', 'Sales  Products', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '401000', 'Sales - Events', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '402000', 'Sales  Subscriptions', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '403000', 'Consulting', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '405000', 'Inventory Adjustment Gain / Stock Gain', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('TEMPLATE', '410000', 'Sales Discounts', 'REVENUE', 'REVENUE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '450000', 'Other Income', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('TEMPLATE', '451000', 'Interest Income', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('TEMPLATE', '452000', 'Supplier Balances Written Off', 'REVENUE', 'REVENUE_OTHER', 'ACTIVE'),
    ('TEMPLATE', '500000', 'Cost of Goods Sold', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('TEMPLATE', '501000', 'Cost of Goods Sold  Labour', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('TEMPLATE', '502000', 'Freight Inwards', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('TEMPLATE', '503000', 'Packaging and Fulfilment Supplies', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('TEMPLATE', '504000', 'Raw Materials Consumed', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('TEMPLATE', '505000', 'Inventory Adjustment Loss', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('TEMPLATE', '506000', 'Samples and Demo Stock Consumed', 'EXPENSE', 'EXPENSE_COGS', 'ACTIVE'),
    ('TEMPLATE', '600000', 'Wages and Salaries', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '601000', 'Payroll Taxes', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '602000', 'Superannuation Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '603000', 'Tax Adjustments', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '610000', 'Bad Debt Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '611000', 'Repairs and Maintenance', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '612000', 'Office Supplies', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '613000', 'Consumables Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '614000', 'Freight and Courier', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '620000', 'Utilities', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '630000', 'IT and Software', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '631000', 'Telecommunications', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '640000', 'Advertising', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '641000', 'Marketing & Promotions', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '650000', 'Professional Fees', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '651000', 'Accounting & Audit Fees', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '699000', 'General Expenses', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE'),
    ('TEMPLATE', '700000', 'Depreciation – Plant & Equipment', 'EXPENSE', 'EXPENSE_DEPRECIATION', 'ACTIVE'),
    ('TEMPLATE', '701000', 'Depreciation – Vehicles', 'EXPENSE', 'EXPENSE_DEPRECIATION', 'ACTIVE'),
    ('TEMPLATE', '710000', 'Amortisation – Software', 'EXPENSE', 'EXPENSE_DEPRECIATION', 'ACTIVE'),
    ('TEMPLATE', '800000', 'Interest Expense', 'EXPENSE', 'EXPENSE_INTEREST', 'ACTIVE'),
    ('TEMPLATE', '810000', 'Bank Fees', 'EXPENSE', 'EXPENSE_INTEREST', 'ACTIVE'),
    ('TEMPLATE', '820000', 'Doubtful Debt Expense', 'EXPENSE', 'EXPENSE_OPERATING', 'ACTIVE')
)
INSERT INTO gl_account (finance_organization_id, code, name, account_type, account_category_id, status, creation_actor_type, updated_actor_type)
SELECT fc.id, s.code, s.name, s.account_type, cat.id, s.status, 'SYSTEM', 'SYSTEM'
FROM seed s
JOIN finance_organization fc ON fc.is_template = TRUE AND s.company_code = 'TEMPLATE'
LEFT JOIN gl_account_category cat ON cat.finance_organization_id = fc.id AND cat.code = s.category_code
ON CONFLICT (finance_organization_id, code) DO UPDATE SET
  name = EXCLUDED.name,
  account_type = EXCLUDED.account_type,
  account_category_id = EXCLUDED.account_category_id,
  status = EXCLUDED.status,
  updated_date = NOW(),
  updated_actor_type = 'SYSTEM';
