INSERT INTO tax_authority (code, name, country_code, region_code, jurisdiction_level, tax_family_code, description, status, creation_actor_type, updated_actor_type)
VALUES
  ('ATO', 'Australian Taxation Office', 'AU', NULL, 'NATIONAL', 'INDIRECT_TAX', 'Australian authority for GST.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CA_BC_FINANCE', 'British Columbia Ministry of Finance', 'CA', 'BC', 'PROVINCIAL', 'INDIRECT_TAX', 'Provincial authority for British Columbia PST.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CA_CRA', 'Canada Revenue Agency', 'CA', NULL, 'FEDERAL', 'INDIRECT_TAX', 'Federal authority for GST and HST. Used for GST-only provinces and HST provinces.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CA_MB_FINANCE', 'Manitoba Finance', 'CA', 'MB', 'PROVINCIAL', 'INDIRECT_TAX', 'Provincial authority for Manitoba Retail Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CA_REVENU_QUEBEC', 'Revenu Québec', 'CA', 'QC', 'PROVINCIAL', 'INDIRECT_TAX', 'Québec authority for QST. Revenu Québec also administers GST/HST in Québec under agreement with the federal government.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CA_SK_FINANCE', 'Saskatchewan Ministry of Finance', 'CA', 'SK', 'PROVINCIAL', 'INDIRECT_TAX', 'Provincial authority for Saskatchewan PST.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('HMRC', 'HM Revenue & Customs', 'GB', NULL, 'NATIONAL', 'INDIRECT_TAX', 'United Kingdom authority for VAT.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IRD', 'Inland Revenue Department', 'NZ', NULL, 'NATIONAL', 'INDIRECT_TAX', 'New Zealand authority for GST.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_AK_TAX', 'Alaska Department of Revenue', 'US', 'AK', 'STATE', 'INDIRECT_TAX', 'State authority for Alaska Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_AL_TAX', 'Alabama Department of Revenue', 'US', 'AL', 'STATE', 'INDIRECT_TAX', 'State authority for Alabama Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_AR_TAX', 'Arkansas Department of Finance', 'US', 'AR', 'STATE', 'INDIRECT_TAX', 'State authority for Arkansas Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_AZ_TAX', 'Arizona Department of Revenue', 'US', 'AZ', 'STATE', 'INDIRECT_TAX', 'State authority for Arizona Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_CA_TAX', 'California Tax and Fee Administration', 'US', 'CA', 'STATE', 'INDIRECT_TAX', 'State authority for California Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_CO_TAX', 'Colorado Department of Revenue', 'US', 'CO', 'STATE', 'INDIRECT_TAX', 'State authority for Colorado Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_CT_TAX', 'Connecticut Department of Revenue Services', 'US', 'CT', 'STATE', 'INDIRECT_TAX', 'State authority for Connecticut Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_DE_TAX', 'Delaware Division of Revenue', 'US', 'DE', 'STATE', 'INDIRECT_TAX', 'State authority for Delaware Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_FL_TAX', 'Florida Department of Revenue', 'US', 'FL', 'STATE', 'INDIRECT_TAX', 'State authority for Florida Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_GA_TAX', 'Georgia Department of Revenue', 'US', 'GA', 'STATE', 'INDIRECT_TAX', 'State authority for Georgia Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_HI_TAX', 'Hawaii Department of Taxation', 'US', 'HI', 'STATE', 'INDIRECT_TAX', 'State authority for Hawaii GET.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_IA_TAX', 'Iowa Department of Revenue', 'US', 'IA', 'STATE', 'INDIRECT_TAX', 'State authority for Iowa Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_ID_TAX', 'Idaho State Tax Commission', 'US', 'ID', 'STATE', 'INDIRECT_TAX', 'State authority for Idaho Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_IL_TAX', 'Illinois Department of Revenue', 'US', 'IL', 'STATE', 'INDIRECT_TAX', 'State authority for Illinois Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_IN_TAX', 'Indiana Department of Revenue', 'US', 'IN', 'STATE', 'INDIRECT_TAX', 'State authority for Indiana Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_KS_TAX', 'Kansas Department of Revenue', 'US', 'KS', 'STATE', 'INDIRECT_TAX', 'State authority for Kansas Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_KY_TAX', 'Kentucky Department of Revenue', 'US', 'KY', 'STATE', 'INDIRECT_TAX', 'State authority for Kentucky Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_LA_TAX', 'Louisiana Department of Revenue', 'US', 'LA', 'STATE', 'INDIRECT_TAX', 'State authority for Louisiana Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_MA_TAX', 'Massachusetts Department of Revenue', 'US', 'MA', 'STATE', 'INDIRECT_TAX', 'State authority for Massachusetts Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_MD_TAX', 'Maryland Comptroller''s Office', 'US', 'MD', 'STATE', 'INDIRECT_TAX', 'State authority for Maryland Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_ME_TAX', 'Maine Revenue Services', 'US', 'ME', 'STATE', 'INDIRECT_TAX', 'State authority for Maine Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_MI_TAX', 'Michigan Department of Treasury', 'US', 'MI', 'STATE', 'INDIRECT_TAX', 'State authority for Michigan Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_MN_TAX', 'Minnesota Department of Revenue', 'US', 'MN', 'STATE', 'INDIRECT_TAX', 'State authority for Minnesota Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_MO_TAX', 'Missouri Department of Revenue', 'US', 'MO', 'STATE', 'INDIRECT_TAX', 'State authority for Missouri Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_MS_TAX', 'Mississippi Department of Revenue', 'US', 'MS', 'STATE', 'INDIRECT_TAX', 'State authority for Mississippi Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_MT_TAX', 'Montana Department of Revenue', 'US', 'MT', 'STATE', 'INDIRECT_TAX', 'State authority for Montana Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_NC_TAX', 'North Carolina Department of Revenue', 'US', 'NC', 'STATE', 'INDIRECT_TAX', 'State authority for North Carolina Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_ND_TAX', 'North Dakota Office of State Tax Commissioner', 'US', 'ND', 'STATE', 'INDIRECT_TAX', 'State authority for North Dakota Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_NE_TAX', 'Nebraska Department of Revenue', 'US', 'NE', 'STATE', 'INDIRECT_TAX', 'State authority for Nebraska Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_NH_TAX', 'New Hampshire Department of Revenue Administration', 'US', 'NH', 'STATE', 'INDIRECT_TAX', 'State authority for New Hampshire Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_NJ_TAX', 'New Jersey Division of Taxation', 'US', 'NJ', 'STATE', 'INDIRECT_TAX', 'State authority for New Jersey Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_NM_TAX', 'New Mexico Taxation and Revenue Department', 'US', 'NM', 'STATE', 'INDIRECT_TAX', 'State authority for New Mexico GRT.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_NV_TAX', 'Nevada Department of Taxation', 'US', 'NV', 'STATE', 'INDIRECT_TAX', 'State authority for Nevada Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_NY_TAX', 'New York Department of Taxation and Finance', 'US', 'NY', 'STATE', 'INDIRECT_TAX', 'State authority for New York Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_OH_TAX', 'Ohio Department of Taxation', 'US', 'OH', 'STATE', 'INDIRECT_TAX', 'State authority for Ohio Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_OK_TAX', 'Oklahoma Tax Commission', 'US', 'OK', 'STATE', 'INDIRECT_TAX', 'State authority for Oklahoma Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_OR_TAX', 'Oregon Department of Revenue', 'US', 'OR', 'STATE', 'INDIRECT_TAX', 'State authority for Oregon Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_PA_TAX', 'Pennsylvania Department of Revenue', 'US', 'PA', 'STATE', 'INDIRECT_TAX', 'State authority for Pennsylvania Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_RI_TAX', 'Rhode Island Division of Taxation', 'US', 'RI', 'STATE', 'INDIRECT_TAX', 'State authority for Rhode Island Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_SC_TAX', 'South Carolina Department of Revenue', 'US', 'SC', 'STATE', 'INDIRECT_TAX', 'State authority for South Carolina Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_SD_TAX', 'South Dakota Department of Revenue', 'US', 'SD', 'STATE', 'INDIRECT_TAX', 'State authority for South Dakota Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_TN_TAX', 'Tennessee Department of Revenue', 'US', 'TN', 'STATE', 'INDIRECT_TAX', 'State authority for Tennessee Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_TX_TAX', 'Texas Comptroller of Public Accounts', 'US', 'TX', 'STATE', 'INDIRECT_TAX', 'State authority for Texas Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_UT_TAX', 'Utah State Tax Commission', 'US', 'UT', 'STATE', 'INDIRECT_TAX', 'State authority for Utah Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_VA_TAX', 'Virginia Department of Taxation', 'US', 'VA', 'STATE', 'INDIRECT_TAX', 'State authority for Virginia Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_VT_TAX', 'Vermont Department of Taxes', 'US', 'VT', 'STATE', 'INDIRECT_TAX', 'State authority for Vermont Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_WA_TAX', 'Washington Department of Revenue', 'US', 'WA', 'STATE', 'INDIRECT_TAX', 'State authority for Washington Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_WI_TAX', 'Wisconsin Department of Revenue', 'US', 'WI', 'STATE', 'INDIRECT_TAX', 'State authority for Wisconsin Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_WV_TAX', 'West Virginia Tax Division', 'US', 'WV', 'STATE', 'INDIRECT_TAX', 'State authority for West Virginia Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US_WY_TAX', 'Wyoming Department of Revenue', 'US', 'WY', 'STATE', 'INDIRECT_TAX', 'State authority for Wyoming Sales Tax.', 'ACTIVE', 'SYSTEM', 'SYSTEM')
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    country_code = EXCLUDED.country_code,
    region_code = EXCLUDED.region_code,
    jurisdiction_level = EXCLUDED.jurisdiction_level,
    tax_family_code = EXCLUDED.tax_family_code,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    updated_date = NOW(),
    updated_actor_type = 'SYSTEM';
