DROP TABLE IF EXISTS tax_ledger_entry_line CASCADE;

CREATE TABLE tax_ledger_entry_line (
    id                              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    tax_ledger_entry_header_id      BIGINT NOT NULL,
    line_number                     INTEGER NOT NULL,
    tax_rule_id                     BIGINT NOT NULL,
    tax_component_id                BIGINT,
    tax_authority_id                BIGINT NOT NULL,
    tax_movement_type_code          business_code NOT NULL,
    scheme_code                     TEXT,
    invoice_label                   TEXT,
    report_label                    TEXT,
    tax_rate                        percentage_decimal NOT NULL,
    taxable_base_currency_amount    money_2dp_pos NOT NULL,
    dr_cr                           dr_cr NOT NULL,
    base_currency_amount            money_2dp_pos NOT NULL,

    creation_date                   audit_timestamp,
    creation_actor_type             actor_type,
    creation_user_id                TEXT,
    creation_mutation_id UUID,

    updated_date                    audit_timestamp,
    updated_actor_type              actor_type,
    updated_user_id                 TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT uq_tax_ledger_entry_line_number UNIQUE (tax_ledger_entry_header_id, line_number),
    CONSTRAINT fk_tax_line_header            FOREIGN KEY (tax_ledger_entry_header_id) REFERENCES tax_ledger_entry_header(id) ON DELETE CASCADE,
    CONSTRAINT fk_tax_line_tax_rule          FOREIGN KEY (tax_rule_id)                REFERENCES tax_rule(id),
    CONSTRAINT fk_tax_line_tax_component     FOREIGN KEY (tax_component_id)           REFERENCES tax_component(id),
    CONSTRAINT fk_tax_line_tax_authority     FOREIGN KEY (tax_authority_id)           REFERENCES tax_authority(id)
);
