DROP TABLE IF EXISTS inventory_ledger_entry_line CASCADE;

CREATE TABLE inventory_ledger_entry_line (
    id                                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    inventory_ledger_entry_header_id    BIGINT NOT NULL,
    line_number                         INTEGER NOT NULL,
    movement_type_code                  business_code NOT NULL,
    item_id                             BIGINT NOT NULL,
    description                         TEXT NOT NULL,
    inventory_control_account_code      business_code NOT NULL DEFAULT 'INVENTORY_CONTROL',
    qty_delta                           NUMERIC(18,6) NOT NULL DEFAULT 0,
    unit_value_supplied                 NUMERIC(18,2),
    book_value_delta                    NUMERIC(18,2) NOT NULL,
    qty_balance                         NUMERIC(18,6) NOT NULL,
    avg_unit_value                      NUMERIC(18,2) NOT NULL,
    book_value_balance                  NUMERIC(18,2) NOT NULL,
    memo                                TEXT,

    creation_date                       audit_timestamp,
    creation_actor_type                 actor_type,
    creation_user_id                    TEXT,
    creation_mutation_id UUID,

    updated_date                        audit_timestamp,
    updated_actor_type                  actor_type,
    updated_user_id                     TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT uq_inventory_ledger_entry_line_number UNIQUE (inventory_ledger_entry_header_id, line_number),
    CONSTRAINT fk_inventory_ledger_line_header
        FOREIGN KEY (inventory_ledger_entry_header_id)
        REFERENCES inventory_ledger_entry_header(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_ledger_line_item
        FOREIGN KEY (item_id)
        REFERENCES inventory_item(id) ON DELETE CASCADE,
    CONSTRAINT inventory_ledger_line_movement_type_allowed CHECK (movement_type_code IN (
        'INVENTORY_RECEIPT',
        'INVENTORY_ISSUE',
        'INVENTORY_QUANTITY_ADJUSTMENT',
        'INVENTORY_VALUE_ADJUSTMENT'
    ))
);
