DROP TABLE IF EXISTS ar_subledger_entry_line CASCADE;

CREATE TABLE ar_subledger_entry_line (
    id                              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    ar_subledger_entry_header_id    BIGINT NOT NULL,
    line_number                     INTEGER NOT NULL,
    line_type                       TEXT NOT NULL CHECK (line_type IN (
                                      'INVOICE_LINE',
                                      'RECEIPT_ALLOCATION',
                                      'RECEIPT_UNAPPLIED',
                                      'RECEIPT_APPLICATION',
                                      'INVOICE_CANCELLATION_LINE',
                                      'CREDIT_NOTE_LINE',
                                      'OPENING_BALANCE_ITEM',
                                      'REFUND_APPLICATION',
                                      'WRITE_OFF_APPLICATION'
                                    )),
    description                     TEXT NOT NULL,
    control_account_code            business_code NOT NULL,
    dr_cr                           dr_cr NOT NULL,
    quantity                        NUMERIC(18,6),
    unit_amount                     NUMERIC(18,6),
    net_amount                      NUMERIC(18,2),
    tax_amount                      NUMERIC(18,2),
    gross_amount                    money_2dp_pos NOT NULL,
    revenue_posting_code            TEXT,
    tax_rule_code                   TEXT,
    source_entry_header_id          BIGINT,
    target_entry_header_id          BIGINT,
    reverses_entry_line_id          BIGINT,
    base_currency_amount            money_2dp_pos NOT NULL,
    memo                            TEXT,

    creation_date                   audit_timestamp,
    creation_actor_type             actor_type,
    creation_user_id                TEXT,
    creation_mutation_id UUID,

    updated_date                    audit_timestamp,
    updated_actor_type              actor_type,
    updated_user_id                 TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT uq_ar_subledger_entry_line_number UNIQUE (ar_subledger_entry_header_id, line_number),
    CONSTRAINT fk_ar_line_header          FOREIGN KEY (ar_subledger_entry_header_id) REFERENCES ar_subledger_entry_header(id) ON DELETE CASCADE,
    CONSTRAINT fk_ar_line_source_header   FOREIGN KEY (source_entry_header_id)       REFERENCES ar_subledger_entry_header(id),
    CONSTRAINT fk_ar_line_target_header   FOREIGN KEY (target_entry_header_id)       REFERENCES ar_subledger_entry_header(id),
    CONSTRAINT fk_ar_line_reverses_line   FOREIGN KEY (reverses_entry_line_id)       REFERENCES ar_subledger_entry_line(id)
);
