DROP TABLE IF EXISTS journal_line_dimension CASCADE;
CREATE TABLE journal_line_dimension (
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    journal_line_id       BIGINT NOT NULL,
    dimension_id          BIGINT NOT NULL,
    dimension_value_id    BIGINT NOT NULL,
    -- Snapshots
    dimension_code        TEXT NOT NULL,
    dimension_name        TEXT NOT NULL,
    dimension_value_name  TEXT NOT NULL,
    -- Audit
    creation_date         audit_timestamp,
    creation_actor_type   actor_type,
    creation_user_id      TEXT,
    creation_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_journal_line    FOREIGN KEY (journal_line_id)    REFERENCES journal_line(id) ON DELETE CASCADE,
    CONSTRAINT fk_dimension       FOREIGN KEY (dimension_id)       REFERENCES dimension(id),
    CONSTRAINT fk_dimension_value FOREIGN KEY (dimension_value_id) REFERENCES dimension_value(id),
    CONSTRAINT fk_dimension_value_dimension
      FOREIGN KEY (dimension_id, dimension_value_id)
      REFERENCES dimension_value(dimension_id, id),
    CONSTRAINT uq_line_dimension  UNIQUE (journal_line_id, dimension_id)
);