CREATE TABLE IF NOT EXISTS company (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code business_code UNIQUE CHECK (length(code) <= 14),
    name display_name NOT NULL,
    country_code iso_country_code NOT NULL,
    base_currency_code iso_currency_code NOT NULL,
    report_line_1 description_text,
    report_line_2 description_text,
    report_footer description_text,
    tax_filing_anchor_month INTEGER NOT NULL DEFAULT 3 CHECK (tax_filing_anchor_month BETWEEN 1 AND 12),
    tax_filing_interval_months INTEGER NOT NULL DEFAULT 3 CHECK (tax_filing_interval_months IN (1, 2, 3, 6, 12)),
    use_organization_standard_settings BOOLEAN NOT NULL DEFAULT TRUE,
    is_template BOOLEAN NOT NULL DEFAULT FALSE,
    status active_status,

    creation_date audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id TEXT,
    creation_mutation_id UUID,

    updated_date audit_timestamp,
    updated_actor_type actor_type,
    updated_user_id TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    organization_id       BIGINT NOT NULL,

    CONSTRAINT fk_country FOREIGN KEY (country_code) REFERENCES country(code),
    CONSTRAINT fk_currency FOREIGN KEY (base_currency_code) REFERENCES currency(code),
    CONSTRAINT fk_organization FOREIGN KEY (organization_id) REFERENCES organization(id)
);
