-- ============================================================
-- Fiscal Period
-- Business domain: Company Accounting > Periods
-- ============================================================

CREATE TABLE IF NOT EXISTS fiscal_period (
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    company_id      BIGINT NOT NULL,
    fiscal_year_id  BIGINT NOT NULL,
    code            business_code,
    name            TEXT NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    status          TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED')),

    -- Audit fields
    creation_date       audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id    TEXT,
    creation_mutation_id UUID,
    updated_date        audit_timestamp,
    updated_actor_type  actor_type,
    updated_user_id     TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_fiscal_year FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_year(id),
    CONSTRAINT uq_year_code UNIQUE (fiscal_year_id, code),
    CONSTRAINT chk_date_range CHECK (start_date <= end_date)
);