-- ============================================================
-- Organization
-- Business domain: Global Settings > Organization
-- Exactly one record per instance.
-- ============================================================

CREATE TABLE IF NOT EXISTS organization (
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code                  business_code NOT NULL UNIQUE,
    organization_name     display_name NOT NULL DEFAULT 'Default Organization',
    status                active_status NOT NULL DEFAULT 'ACTIVE',

    -- Created audit stamp
    creation_date         audit_timestamp,
    creation_actor_type   actor_type,
    creation_user_id      TEXT,
    creation_mutation_id  UUID,

    -- Updated audit stamp
    updated_date          audit_timestamp,
    updated_actor_type    actor_type,
    updated_user_id       TEXT,
    updated_mutation_id   UUID,

    -- Delete audit handoff only, for hard deletes
    deletion_date         audit_timestamp,
    deletion_actor_type   actor_type,
    deletion_user_id      TEXT,
    deletion_mutation_id  UUID
);
