CREATE TABLE IF NOT EXISTS journal_line (
    id                          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    journal_header_id           BIGINT NOT NULL,
    line_number                 INTEGER NOT NULL,
    gl_account_id               BIGINT NOT NULL,
    gl_account_code             TEXT NOT NULL,
    gl_account_name             TEXT NOT NULL,
    source_ledger               TEXT,
    source_control_account      TEXT,
    dr_cr                       dr_cr NOT NULL,
    base_currency_amount        NUMERIC(18,2) NOT NULL CHECK (base_currency_amount >= 0),
    description                 TEXT NOT NULL,
    memo                        TEXT,

    creation_date               audit_timestamp,
    creation_actor_type         actor_type,
    creation_user_id            TEXT,
    creation_mutation_id UUID,

    updated_date                audit_timestamp,
    updated_actor_type          actor_type,
    updated_user_id             TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT uq_journal_line_header_line  UNIQUE (journal_header_id, line_number),
    CONSTRAINT fk_journal_header            FOREIGN KEY (journal_header_id) REFERENCES journal_header(id),
    CONSTRAINT fk_gl_account                FOREIGN KEY (gl_account_id)     REFERENCES gl_account(id)
);
