import type { DbExecutor } from "@voyzu/capability/db";

type Lookup = "company" | "documentProcessor" | "counterparty" | "period" | "control" | "documentDefault" | "bankOverride" | "glOverride" | "defaultAccount" | "openBill" | "openPayment" | "taxControl" | "taxSetup";
const SQL: Record<Lookup, string> = {
  company: `SELECT fc.id, c.code, c.name, c.country_code, c.base_currency_code, c.status FROM finance_organization fc JOIN organization c ON c.id = fc.organization_id WHERE c.code = $1 AND fc.is_template = false`,
  documentProcessor: `SELECT code, status, supports_dimensions, cash_movement, supports_items FROM financial_document_type WHERE code = $1`,
  counterparty: `SELECT * FROM ap_counterparty WHERE finance_organization_id = $1 AND code = $2`,
  period: `SELECT fy.id AS financial_year_id, fy.code AS financial_year_code, fp.id AS financial_period_id, fp.code AS financial_period_code FROM fiscal_period fp JOIN fiscal_year fy ON fy.id = fp.fiscal_year_id WHERE fp.finance_organization_id = $1 AND $2::date BETWEEN fp.start_date AND fp.end_date AND fp.status = 'OPEN' AND fy.status = 'OPEN' LIMIT 1`,
  control: `SELECT ca.code AS control_account_code, ca.name AS control_account_name, ga.id AS gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM ap_control_account ca JOIN gl_account ga ON ga.finance_organization_id = ca.finance_organization_id AND ga.id = ca.gl_account_id WHERE ca.finance_organization_id = $1 AND ca.code = $2 AND ca.status = 'ACTIVE' AND ga.status = 'ACTIVE'`,
  documentDefault: `SELECT target_type, allowed_account_types FROM financial_document_default WHERE finance_organization_id = $1 AND document_code = $2 AND code = $3 AND status = 'ACTIVE' LIMIT 1`,
  bankOverride: `SELECT $3::text AS code, bca.code AS bank_cash_control_account_code, bca.gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM bank_cash_control_account bca JOIN gl_account ga ON ga.finance_organization_id = bca.finance_organization_id AND ga.id = bca.gl_account_id WHERE bca.finance_organization_id = $1 AND bca.code = $2 AND bca.status = 'ACTIVE' AND ga.status = 'ACTIVE' AND ga.account_type = ANY($4::text[]) LIMIT 1`,
  glOverride: `SELECT $3::text AS code, ga.id AS gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM gl_account ga WHERE ga.finance_organization_id = $1 AND ga.code = $2 AND ga.status = 'ACTIVE' AND ga.account_type = ANY($4::text[]) LIMIT 1`,
  defaultAccount: `SELECT pc.code, bca.code AS bank_cash_control_account_code, COALESCE(pc.gl_account_id, bca.gl_account_id) AS gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM financial_document_default pc LEFT JOIN bank_cash_control_account bca ON bca.finance_organization_id = pc.finance_organization_id AND bca.id = pc.bank_cash_control_account_id JOIN gl_account ga ON ga.finance_organization_id = pc.finance_organization_id AND ga.id = COALESCE(pc.gl_account_id, bca.gl_account_id) WHERE pc.finance_organization_id = $1 AND pc.document_code = $2 AND pc.code = $3 AND pc.status = 'ACTIVE' AND (bca.id IS NULL OR bca.status = 'ACTIVE') AND ga.status = 'ACTIVE' LIMIT 1`,
  openBill: `SELECT e.id, e.code, h.document_type_code, h.document_id, h.code AS journal_code, h.detailed_document_snapshot_json AS original_bill, GREATEST(COALESCE(bill.amount, 0) - COALESCE(applied.amount, 0), 0)::float AS open_amount FROM ap_subledger_entry_header e JOIN journal_header h ON h.id = e.journal_header_id LEFT JOIN LATERAL (SELECT SUM(base_currency_amount) AS amount FROM ap_subledger_entry_line l WHERE l.ap_subledger_entry_header_id = e.id AND l.control_account_code = $4 AND l.dr_cr = 'CR') bill ON true LEFT JOIN LATERAL (SELECT SUM(base_currency_amount) AS amount FROM ap_subledger_entry_line l WHERE l.target_entry_header_id = e.id AND l.control_account_code = $4 AND l.dr_cr = 'DR') applied ON true WHERE e.finance_organization_id = $1 AND e.ap_counterparty_id = $2 AND h.document_type_code IN ('AP_BILL', 'AP_OPENING_BALANCE') AND h.document_id = $3 LIMIT 1`,
  openPayment: `SELECT e.id, e.code, h.document_type_code, h.document_id, h.code AS journal_code, GREATEST(COALESCE(pay.amount, 0) - COALESCE(used.amount, 0), 0)::float AS open_amount FROM ap_subledger_entry_header e JOIN journal_header h ON h.id = e.journal_header_id LEFT JOIN LATERAL (SELECT SUM(base_currency_amount) AS amount FROM ap_subledger_entry_line l WHERE l.ap_subledger_entry_header_id = e.id AND l.control_account_code = $4 AND l.dr_cr = 'DR') pay ON true LEFT JOIN LATERAL (SELECT SUM(base_currency_amount) AS amount FROM ap_subledger_entry_line l WHERE l.source_entry_header_id = e.id AND l.control_account_code = $4 AND l.dr_cr = 'CR') used ON true WHERE e.finance_organization_id = $1 AND e.ap_counterparty_id = $2 AND h.document_type_code IN ('AP_PAYMENT', 'AP_CREDIT_NOTE') AND h.document_id = $3 LIMIT 1`,
  taxControl: `SELECT ga.id AS gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM tax_control_account tmt JOIN gl_account ga ON ga.finance_organization_id = tmt.finance_organization_id AND ga.id = tmt.gl_account_id WHERE tmt.finance_organization_id = $1 AND tmt.code = $2 AND tmt.status = 'ACTIVE' AND ga.status = 'ACTIVE'`,
  taxSetup: `SELECT tr.id AS tax_rule_id, ta.id AS tax_authority_id, ta.code AS tax_authority_code, ta.name AS tax_authority_name FROM tax_rule tr JOIN tax_authority ta ON ta.country_code = tr.country_code AND ta.code = $3 AND ta.status = 'ACTIVE' WHERE tr.country_code = $1 AND tr.code = $2 AND tr.status = 'ACTIVE' LIMIT 1`,
};

export class ApProcessingRepo {
  constructor(private readonly db: DbExecutor) {}
  async one<T>(lookup: Lookup, params: unknown[], map: (row: Record<string, unknown>) => T): Promise<T | null> { const { rows } = await this.db.query(SQL[lookup], params); return rows[0] ? map(rows[0] as Record<string, unknown>) : null; }
  async many<T>(sql: "taxRules" | "taxComponents" | "taxAuthorities", params: unknown[], map: (row: Record<string, unknown>) => T): Promise<T[]> {
    const statements = {
      taxRules: `SELECT * FROM tax_rule WHERE country_code = $1 AND code = ANY($2::text[])`,
      taxComponents: `SELECT tc.*, ta.id AS tax_authority_id, ta.name AS tax_authority_name FROM tax_component tc JOIN tax_authority ta ON ta.code = tc.tax_authority_code WHERE tc.tax_rule_country_code = $1 AND tc.tax_rule_code = ANY($2::text[]) ORDER BY tc.tax_rule_code ASC, tc.calculation_order ASC`,
      taxAuthorities: `SELECT id, code, name, country_code, status FROM tax_authority WHERE country_code = $1 AND code = ANY($2::text[])`,
    };
    const { rows } = await this.db.query(statements[sql], params); return rows.map((r) => map(r as Record<string, unknown>));
  }
  async unappliedBalance(companyId: number, counterpartyId: number, controlCode: string): Promise<number> { const { rows } = await this.db.query(`SELECT GREATEST(COALESCE(SUM(CASE WHEN l.control_account_code = $3 AND l.dr_cr = 'DR' THEN l.base_currency_amount WHEN l.control_account_code = $3 AND l.dr_cr = 'CR' THEN -l.base_currency_amount ELSE 0 END), 0), 0)::float AS amount FROM ap_subledger_entry_header e JOIN ap_subledger_entry_line l ON l.ap_subledger_entry_header_id = e.id WHERE e.finance_organization_id = $1 AND e.ap_counterparty_id = $2`, [companyId, counterpartyId, controlCode]); return Number(rows[0]?.amount ?? 0); }
  async insertApHeader(params: unknown[]): Promise<number> { const { rows } = await this.db.query(`INSERT INTO ap_subledger_entry_header (code, finance_organization_id, journal_header_id, ap_counterparty_id, document_type_code, document_id, supplier_invoice_number, description, memo, document_date, posting_date, financial_year_id, financial_period_id, base_currency_code, status, creation_date, creation_actor_type) VALUES ($1,$2,$3,$4,$5,$6,NULL,$7,$8,$9,$10,$11,$12,$13,'POSTED',now(),'SYSTEM') RETURNING id`, params); return Number(rows[0].id); }
  async insertApLine(params: unknown[]): Promise<number> { const { rows } = await this.db.query(`INSERT INTO ap_subledger_entry_line (ap_subledger_entry_header_id, line_number, line_type, description, control_account_code, dr_cr, gross_amount, source_entry_header_id, target_entry_header_id, base_currency_amount, memo, creation_date, creation_actor_type) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,now(),'SYSTEM') RETURNING id`, params); return Number(rows[0].id); }
  async insertTaxHeader(params: unknown[]): Promise<number> { const { rows } = await this.db.query(`INSERT INTO tax_ledger_entry_header (code, finance_organization_id, journal_header_id, document_type_code, document_id, description, document_date, posting_date, financial_year_id, financial_period_id, base_currency_code, status, creation_date, creation_actor_type) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'POSTED',now(),'SYSTEM') RETURNING id`, params); return Number(rows[0].id); }
  async insertTaxLine(params: unknown[]): Promise<number> { const { rows } = await this.db.query(`INSERT INTO tax_ledger_entry_line (tax_ledger_entry_header_id, line_number, tax_rule_id, tax_component_id, tax_authority_id, tax_movement_type_code, scheme_code, invoice_label, report_label, tax_rate, taxable_base_currency_amount, dr_cr, base_currency_amount, creation_date, creation_actor_type) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,now(),'SYSTEM') RETURNING id`, params); return Number(rows[0].id); }
}
