export const pageRoutes = {
  "voyzu.commercial.products.page.categoryDetail": { path: "/commercial/products/product-categories/[code]", pathParams: { code: { type: "string" } }, pageTitle: "Product Categories", loadPage: () => import("./server/pages/ProductConfigurationDetailPages").then((module) => module.ProductCategoryDetailPage), breadcrumbBase: [{ label: "Commercial" }, { label: "Products", href: "/commercial/products" }, { label: "Product Categories", href: "/commercial/products/product-categories" }], auth: { required: true, minRole: "STANDARD" } },
  "voyzu.commercial.products.page.listDetail": { path: "/commercial/products/manage-lists/[code]", pathParams: { code: { type: "string" } }, pageTitle: "Manage Lists", loadPage: () => import("./server/pages/ProductConfigurationDetailPages").then((module) => module.ProductListDetailPage), breadcrumbBase: [{ label: "Commercial" }, { label: "Products", href: "/commercial/products" }, { label: "Manage Lists", href: "/commercial/products/manage-lists" }], auth: { required: true, minRole: "STANDARD" } },
  "voyzu.commercial.products.page.optionListDetail": { path: "/commercial/products/option-lists/[code]", pathParams: { code: { type: "string" } }, pageTitle: "Product Option Lists", loadPage: () => import("./server/pages/ProductConfigurationDetailPages").then((module) => module.ProductOptionListDetailPage), breadcrumbBase: [{ label: "Commercial" }, { label: "Products", href: "/commercial/products" }, { label: "Product Option Lists", href: "/commercial/products/option-lists" }], auth: { required: true, minRole: "STANDARD" } },

  "voyzu.commercial.products.page.productDetail": {
    path: "/commercial/products/[code]",
    pathParams: { code: { type: "string" } },
    pageTitle: "Product",
    loadPage: () => import("./server/pages/ProductDetailPage").then((module) => module.ProductDetailPage),
    breadcrumbBase: [{ label: "Commercial" }, { label: "Products", href: "/commercial/products" }],
    auth: { required: true, minRole: "STANDARD" },
  },
  "voyzu.commercial.products.page.manageLists": {
    path: "/commercial/products/manage-lists",
    pageTitle: "Manage Lists",
    loadPage: () => import("./server/pages/ProductConfigurationPages").then((module) => module.ManageListsPage),
    breadcrumbBase: [{ label: "Commercial" }, { label: "Products", href: "/commercial/products" }],
    auth: { required: true, minRole: "STANDARD" },
  },
  "voyzu.commercial.products.page.productCategories": {
    path: "/commercial/products/product-categories",
    pageTitle: "Product Categories",
    loadPage: () => import("./server/pages/ProductConfigurationPages").then((module) => module.ProductCategoriesPage),
    breadcrumbBase: [{ label: "Commercial" }, { label: "Products", href: "/commercial/products" }],
    auth: { required: true, minRole: "STANDARD" },
  },
  "voyzu.commercial.products.page.products": {
    path: "/commercial/products",
    queryParams: { pricingCategory: { type: "string" }, status: { type: "string" } },
    pageTitle: "Products",
    loadPage: () => import("./server/pages/ProductsPage").then((module) => module.ProductsPage),
    breadcrumbBase: [{ label: "Commercial" }],
    auth: { required: true, minRole: "STANDARD" },
  },
  "voyzu.commercial.products.page.productOptions": {
    path: "/commercial/products/options",
    pageTitle: "Product Options",
    loadPage: () => import("./server/pages/ProductOptionsPage").then((module) => module.ProductOptionsPage),
    breadcrumbBase: [{ label: "Commercial" }, { label: "Products" }],
    auth: { required: true, minRole: "STANDARD" },
  },
  "voyzu.commercial.products.page.productOptionLists": {
    path: "/commercial/products/option-lists",
    pageTitle: "Product Option Lists",
    loadPage: () => import("./server/pages/ProductOptionListsPage").then((module) => module.ProductOptionListsPage),
    breadcrumbBase: [{ label: "Commercial" }, { label: "Products" }],
    auth: { required: true, minRole: "STANDARD" },
  },
} as const;
