import { handleProcessApBill, handleProcessApBillCancellation, handleProcessApCreditNote, handleProcessApOpeningBalance, handleProcessApPayment, handleProcessApPaymentApplication, handleProcessApRefund, handleProcessApWriteOff, handleProcessArCreditNote, handleProcessArInvoice, handleProcessArInvoiceCancellation, handleProcessArOpeningBalance, handleProcessArReceipt, handleProcessArReceiptApplication, handleProcessArRefund, handleProcessArWriteOff, handleProcessInventoryAdjustment, handleProcessInventoryIssue, handleProcessInventoryReceipt, handleProcessLedgerJournal, handleProcessLedgerJournalReversal, handleProcessTaxAdjustment, handleProcessTaxPayment, handleProcessTaxRefund } from "@voyzu-modules/core/financial-document-processing-engine/server";
import { dtoRef } from "@voyzu/types/api";

export const financialDocumentProcessingEngineModule = {
  id: "voyzu.financial-document-processing-engine",
  name: "Financial Document Processing Engine",
  apiDefinitions: {
    apBill: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_BILL",
      handler: (request: any) => handleProcessApBill(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Bill",
        description: "AP Bill Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApBillRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApBillPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    apBillCancellation: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_BILL_CANCELLATION",
      handler: (request: any) => handleProcessApBillCancellation(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Bill Cancellation",
        description: "AP Bill Cancellation Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApBillCancellationRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    apCreditNote: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_CREDIT_NOTE",
      handler: (request: any) => handleProcessApCreditNote(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Credit Note",
        description: "AP Credit Note Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApCreditNoteRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    apOpeningBalance: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_OPENING_BALANCE",
      handler: (request: any) => handleProcessApOpeningBalance(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Opening Balance",
        description: "AP Opening Balance Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApOpeningBalanceRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    apPayment: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_PAYMENT",
      handler: (request: any) => handleProcessApPayment(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Payment",
        description: "AP Payment Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApPaymentRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    apPaymentApplication: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_PAYMENT_APPLICATION",
      handler: (request: any) => handleProcessApPaymentApplication(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Payment Application",
        description: "AP Payment Application Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApPaymentApplicationRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    apRefund: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_REFUND",
      handler: (request: any) => handleProcessApRefund(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Refund",
        description: "AP Refund Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApRefundRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    apWriteOff: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AP_WRITE_OFF",
      handler: (request: any) => handleProcessApWriteOff(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AP Write Off",
        description: "AP Write Off Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ApWriteOffRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ApProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arCreditNote: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_CREDIT_NOTE",
      handler: (request: any) => handleProcessArCreditNote(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Credit Note",
        description: "AR Credit Note Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArCreditNoteRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArAdjustmentPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arInvoice: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_INVOICE",
      handler: (request: any) => handleProcessArInvoice(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Invoice",
        description: "AR Invoice Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArInvoiceRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArInvoicePostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arInvoiceCancellation: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_INVOICE_CANCELLATION",
      handler: (request: any) => handleProcessArInvoiceCancellation(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Invoice Cancellation",
        description: "AR Invoice Cancellation Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArInvoiceCancellationRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArInvoiceCancellationPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arOpeningBalance: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_OPENING_BALANCE",
      handler: (request: any) => handleProcessArOpeningBalance(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Opening Balance",
        description: "AR Opening Balance Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArOpeningBalanceRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArAdjustmentPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arReceipt: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_RECEIPT",
      handler: (request: any) => handleProcessArReceipt(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Receipt",
        description: "AR Receipt Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArReceiptRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArReceiptPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arReceiptApplication: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_RECEIPT_APPLICATION",
      handler: (request: any) => handleProcessArReceiptApplication(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Receipt Application",
        description: "AR Receipt Application Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArReceiptApplicationRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArReceiptApplicationPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arRefund: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_REFUND",
      handler: (request: any) => handleProcessArRefund(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Refund",
        description: "AR Refund Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArRefundRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArAdjustmentPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    arWriteOff: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/AR_WRITE_OFF",
      handler: (request: any) => handleProcessArWriteOff(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "AR Write Off",
        description: "AR Write Off Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("ArWriteOffRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("ArAdjustmentPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    inventoryAdjustment: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/INVENTORY_ADJUSTMENT",
      handler: (request: any) => handleProcessInventoryAdjustment(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Inventory Adjustment",
        description: "Inventory Adjustment Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("InventoryAdjustmentRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("InventoryProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    inventoryIssue: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/INVENTORY_ISSUE",
      handler: (request: any) => handleProcessInventoryIssue(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Inventory Issue",
        description: "Inventory Issue Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("InventoryIssueRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("InventoryProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    inventoryReceipt: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/INVENTORY_RECEIPT",
      handler: (request: any) => handleProcessInventoryReceipt(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Inventory Receipt",
        description: "Inventory Receipt Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("InventoryReceiptRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("InventoryProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    ledgerJournal: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/LEDGER_JOURNAL",
      handler: (request: any) => handleProcessLedgerJournal(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Ledger Journal",
        description: "Ledger Journal Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("LedgerJournalRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("LedgerJournalPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    ledgerJournalReversal: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/LEDGER_JOURNAL_REVERSAL",
      handler: (request: any) => handleProcessLedgerJournalReversal(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Ledger Journal Reversal",
        description: "Ledger Journal Reversal Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("LedgerJournalReversalRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("LedgerJournalReversalPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    taxAdjustment: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/TAX_ADJUSTMENT",
      handler: (request: any) => handleProcessTaxAdjustment(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Tax Adjustment",
        description: "Tax Adjustment Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("TaxAdjustmentRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("TaxProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    taxPayment: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/TAX_PAYMENT",
      handler: (request: any) => handleProcessTaxPayment(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Tax Payment",
        description: "Tax Payment Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("TaxPaymentRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("TaxProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
    taxRefund: {
      method: "POST",
      path: "/finance/[companyCode]/process-document/TAX_REFUND",
      handler: (request: any) => handleProcessTaxRefund(request),
      apiDoc: { requestPathParams: { companyCode: { description: "Company code that identifies the company scope for this finance API call.", schema: { type: "string" } } },
        summary: "Tax Refund",
        description: "Tax Refund Financial Document Processing Engine.",
        tags: ["Financial Document Processing Engine"],
        requestBody: { required: true, schema: dtoRef("TaxRefundRequestDto") },
        responses: {
          "200": { description: "Posted financial document result.", schema: dtoRef("TaxProcessingPostingResponseDto") }, "400": { description: "Validation failed.", schema: dtoRef("InputValidationErrorResponseDto") },
          "404": { description: "Entity not found.", schema: dtoRef("EntityNotFoundErrorResponseDto") },
          "422": { description: "Business rule failed.", schema: dtoRef("BusinessRuleErrorResponseDto") },
          "500": { description: "An unexpected server error occurred.", schema: dtoRef("InternalServerErrorResponseDto") }
        },
      },
    },
  }
} as const;
