import type { DbExecutor } from "@voyzu/capability/db";
import type { ArInvoiceDetailedInvoiceDto } from "@voyzu/finance/types/modules/financial-document-processing-engine/ar-invoice.response.dto";

type CompanyRow = { id: number; code: string; name: string; base_currency_code: string; status: string };
type CounterpartyRow = { id: number; finance_organization_id: number; code: string; name: string; status: string };
type PeriodRow = { financial_year_id: number; financial_year_code: string; financial_period_id: number; financial_period_code: string };
type AccountRow = { gl_account_id: number; gl_account_code: string; gl_account_name: string; control_account_code: string; control_account_name: string };
type TaxAccountRow = { gl_account_id: number; gl_account_code: string; gl_account_name: string; tax_movement_type_code: string };
type PostingCodeRow = { code: string; gl_account_id: number; gl_account_code: string; gl_account_name: string };
type DimensionValueRow = { dimension_id: number; dimension_code: string; dimension_name: string; dimension_value_id: number; dimension_value_name: string };
type OpenInvoiceRow = { ar_subledger_entry_id: number; ar_subledger_entry_code: string; journal_header_id: number; document_id: string; journal_code: string; posting_date: string; base_currency_amount: number; open_amount: number; original_invoice: ArInvoiceDetailedInvoiceDto };

function dateString(value: unknown) { return value instanceof Date ? value.toISOString().slice(0, 10) : String(value); }

export class ArInvoiceCancellationPostingRepo {
  constructor(readonly db: DbExecutor) {}

  private async one<T>(sql: string, params: unknown[], map: (row: Record<string, unknown>) => T): Promise<T | null> {
    const { rows } = await this.db.query(sql, params);
    return rows[0] ? map(rows[0] as Record<string, unknown>) : null;
  }

  getCompany(code: string) { return this.one(`SELECT fc.id, c.code, c.name, c.base_currency_code, c.status FROM finance_organization fc JOIN organization c ON c.id = fc.organization_id WHERE c.code = $1`, [code], (r): CompanyRow => ({ id: Number(r.id), code: String(r.code), name: String(r.name), base_currency_code: String(r.base_currency_code), status: String(r.status) })); }
  getCounterparty(companyId: number, code: string) { return this.one(`SELECT id, finance_organization_id, code, name, status FROM ar_counterparty WHERE finance_organization_id = $1 AND code = $2`, [companyId, code], (r): CounterpartyRow => ({ id: Number(r.id), finance_organization_id: Number(r.finance_organization_id), code: String(r.code), name: String(r.name), status: String(r.status) })); }
  getPeriod(companyId: number, postingDate: string) { return this.one(`SELECT fy.id AS financial_year_id, fy.code AS financial_year_code, fp.id AS financial_period_id, fp.code AS financial_period_code FROM fiscal_period fp JOIN fiscal_year fy ON fy.id = fp.fiscal_year_id WHERE fp.finance_organization_id = $1 AND $2::date BETWEEN fp.start_date AND fp.end_date AND fy.status = 'OPEN' AND fp.status = 'OPEN' LIMIT 1`, [companyId, postingDate], (r): PeriodRow => ({ financial_year_id: Number(r.financial_year_id), financial_year_code: String(r.financial_year_code), financial_period_id: Number(r.financial_period_id), financial_period_code: String(r.financial_period_code) })); }
  getArControlAccount(companyId: number, code: string) { return this.one(`SELECT ca.code AS control_account_code, ca.name AS control_account_name, ca.gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM ar_control_account ca JOIN gl_account ga ON ga.finance_organization_id = ca.finance_organization_id AND ga.id = ca.gl_account_id WHERE ca.finance_organization_id = $1 AND ca.code = $2 AND ca.status = 'ACTIVE' AND ga.status = 'ACTIVE'`, [companyId, code], (r): AccountRow => ({ gl_account_id: Number(r.gl_account_id), gl_account_code: String(r.gl_account_code), gl_account_name: String(r.gl_account_name), control_account_code: String(r.control_account_code), control_account_name: String(r.control_account_name) })); }
  getTaxMovementAccount(companyId: number, code: string) { return this.one(`SELECT tmt.code AS tax_movement_type_code, tmt.gl_account_id AS gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM tax_control_account tmt JOIN gl_account ga ON ga.finance_organization_id = tmt.finance_organization_id AND ga.id = tmt.gl_account_id WHERE tmt.finance_organization_id = $1 AND tmt.code = $2 AND tmt.status = 'ACTIVE' AND ga.status = 'ACTIVE' LIMIT 1`, [companyId, code], (r): TaxAccountRow => ({ gl_account_id: Number(r.gl_account_id), gl_account_code: String(r.gl_account_code), gl_account_name: String(r.gl_account_name), tax_movement_type_code: String(r.tax_movement_type_code) })); }
  getOpenInvoice(companyId: number, counterpartyId: number, documentId: string, controlCode: string) { return this.one(`SELECT e.id AS ar_subledger_entry_id, e.code AS ar_subledger_entry_code, e.journal_header_id, h.document_id, h.code AS journal_code, h.posting_date, COALESCE(invoice_lines.amount, 0)::float AS base_currency_amount, GREATEST(COALESCE(invoice_lines.amount, 0) - COALESCE(applied_lines.amount, 0), 0)::float AS open_amount, h.detailed_document_snapshot_json AS original_invoice FROM ar_subledger_entry_header e JOIN journal_header h ON h.id = e.journal_header_id LEFT JOIN LATERAL (SELECT SUM(l.base_currency_amount) AS amount FROM ar_subledger_entry_line l WHERE l.ar_subledger_entry_header_id = e.id AND l.control_account_code = $4 AND l.dr_cr = 'DR') invoice_lines ON true LEFT JOIN LATERAL (SELECT SUM(l.base_currency_amount) AS amount FROM ar_subledger_entry_line l WHERE l.target_entry_header_id = e.id AND l.control_account_code = $4 AND l.dr_cr = 'CR') applied_lines ON true WHERE e.finance_organization_id = $1 AND e.ar_counterparty_id = $2 AND h.document_type_code = 'AR_INVOICE' AND h.status = 'POSTED' AND h.document_id = $3 LIMIT 1`, [companyId, counterpartyId, documentId, controlCode], (r): OpenInvoiceRow => ({ ar_subledger_entry_id: Number(r.ar_subledger_entry_id), ar_subledger_entry_code: String(r.ar_subledger_entry_code), journal_header_id: Number(r.journal_header_id), document_id: String(r.document_id), journal_code: String(r.journal_code), posting_date: dateString(r.posting_date), base_currency_amount: Number(r.base_currency_amount), open_amount: Number(r.open_amount), original_invoice: r.original_invoice as ArInvoiceDetailedInvoiceDto })); }

  async listRevenuePostingCodes(companyId: number, codes: string[]): Promise<PostingCodeRow[]> {
    if (codes.length === 0) return [];
    const { rows } = await this.db.query(`SELECT ga.code, ga.id AS gl_account_id, ga.code AS gl_account_code, ga.name AS gl_account_name FROM gl_account ga WHERE ga.finance_organization_id = $1 AND ga.status = 'ACTIVE' AND ga.account_type = 'REVENUE' AND ga.code = ANY($2::text[])`, [companyId, codes]);
    return rows.map((r): PostingCodeRow => ({ code: String(r.code), gl_account_id: Number(r.gl_account_id), gl_account_code: String(r.gl_account_code), gl_account_name: String(r.gl_account_name) }));
  }
  async listDimensionValues(companyId: number, pairs: Array<{ dimensionCode: string; valueName: string }>): Promise<DimensionValueRow[]> {
    if (pairs.length === 0) return [];
    const { rows } = await this.db.query(`SELECT d.id AS dimension_id, d.code AS dimension_code, d.name AS dimension_name, dv.id AS dimension_value_id, dv.name AS dimension_value_name FROM dimension d JOIN dimension_value dv ON dv.finance_organization_id = d.finance_organization_id AND dv.dimension_id = d.id JOIN jsonb_to_recordset($1::jsonb) AS requested(dimension_code text, value_name text) ON requested.dimension_code = d.code AND requested.value_name = dv.name WHERE d.finance_organization_id = $2`, [JSON.stringify(pairs.map((p) => ({ dimension_code: p.dimensionCode, value_name: p.valueName }))), companyId]);
    return rows.map((r): DimensionValueRow => ({ dimension_id: Number(r.dimension_id), dimension_code: String(r.dimension_code), dimension_name: String(r.dimension_name), dimension_value_id: Number(r.dimension_value_id), dimension_value_name: String(r.dimension_value_name) }));
  }

  async insertArHeader(params: unknown[]): Promise<number> { const { rows } = await this.db.query(`INSERT INTO ar_subledger_entry_header (code, finance_organization_id, journal_header_id, ar_counterparty_id, document_type_code, document_id, description, memo, document_date, posting_date, financial_year_id, financial_period_id, base_currency_code, status, creation_date, creation_actor_type) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'POSTED',now(),'SYSTEM') RETURNING id`, params); return Number(rows[0].id); }
  async originalInvoiceLineIds(sourceHeaderId: number): Promise<Map<number, number>> { const { rows } = await this.db.query(`SELECT line_number, id FROM ar_subledger_entry_line WHERE ar_subledger_entry_header_id = $1 AND line_type = 'INVOICE_LINE'`, [sourceHeaderId]); return new Map(rows.map((r) => [Number(r.line_number), Number(r.id)])); }
  insertCancellationLine(params: unknown[]): Promise<unknown> { return this.db.query(`INSERT INTO ar_subledger_entry_line (ar_subledger_entry_header_id, line_number, line_type, description, control_account_code, dr_cr, quantity, unit_amount, net_amount, tax_amount, gross_amount, revenue_posting_code, tax_rule_code, target_entry_header_id, reverses_entry_line_id, base_currency_amount, memo, creation_date, creation_actor_type) VALUES ($1,$2,'INVOICE_CANCELLATION_LINE',$3,$4,'CR',$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,now(),'SYSTEM')`, params); }
  async insertTaxHeader(params: unknown[]): Promise<number> { const { rows } = await this.db.query(`INSERT INTO tax_ledger_entry_header (code, finance_organization_id, journal_header_id, document_type_code, document_id, description, document_date, posting_date, financial_year_id, financial_period_id, base_currency_code, status, creation_date, creation_actor_type) VALUES ($1,$2,$3,'AR_INVOICE_CANCELLATION',$4,$5,$6,$7,$8,$9,$10,'POSTED',now(),'SYSTEM') RETURNING id`, params); return Number(rows[0].id); }
  async insertTaxLine(params: unknown[]): Promise<number> { const { rows } = await this.db.query(`INSERT INTO tax_ledger_entry_line (tax_ledger_entry_header_id, line_number, tax_rule_id, tax_component_id, tax_authority_id, tax_movement_type_code, scheme_code, invoice_label, report_label, tax_rate, taxable_base_currency_amount, dr_cr, base_currency_amount, creation_date, creation_actor_type) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'DR',$12,now(),'SYSTEM') RETURNING id`, params); return Number(rows[0].id); }
}
