export {
  handleActivate,
  handleBatchActivate,
  handleBatchCreate,
  handleBatchDeactivate,
  handleBatchDelete,
  handleBatchGet,
  handleBatchPatch,
  handleBatchUpdate,
  handleCreate,
  handleDeactivate,
  handleDelete,
  handleFilter,
  handleGet,
  handleList,
  handlePatch,
  handleSearch,
  handleUpdate,
} from "./api/template.http.handlers";

export {
  activateTemplate,
  activateTemplates,
  batchCreateTemplates,
  batchDeleteTemplates,
  batchGetTemplates,
  batchPatchTemplates,
  batchUpdateTemplates,
  createTemplate,
  deactivateTemplate,
  deactivateTemplates,
  deleteTemplate,
  filterTemplates,
  getTemplate,
  listTemplates,
  patchTemplate,
  searchTemplates,
  updateTemplate,
} from "./lib/template.service";
