export {
  handleActivate,
  handleBatchActivate,
  handleBatchCreate,
  handleBatchDeactivate,
  handleBatchDelete,
  handleBatchGet,
  handleBatchPatch,
  handleBatchUpdate,
  handleCreate,
  handleCreateValue,
  handleDeactivate,
  handleDelete,
  handleDeleteValue,
  handleFilter,
  handleGet,
  handleList,
  handleListValues,
  handlePatch,
  handlePatchValue,
  handleSearch,
  handleUpdate,
} from "./api/dimension.http.handlers";
export {
  activateDimension,
  activateDimensions,
  batchCreateDimensions,
  batchDeleteDimensions,
  batchGetDimensions,
  batchPatchDimensions,
  batchUpdateDimensions,
  createDimension,
  createDimensionValue,
  deactivateDimension,
  deactivateDimensions,
  deleteDimension,
  deleteDimensionValue,
  filterDimensions,
  getDimension,
  listDimensions,
  listDimensionValues,
  patchDimension,
  patchDimensionValue,
  searchDimensions,
  updateDimension,
} from "./lib/dimension.service";
