"use client";

import { useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { AuditPanel } from "@voyzu/audit/client";
import { Badge, Breadcrumbs, Button, Checkbox, ConfirmDialog, Input, SearchableSelect, TabGroup, Toast, ValidationAlert, required, useFormValidation } from "@voyzu/ui-components";
import { DetailBackButton, detailLinkWithBackContext } from "@voyzu/ui-surface/client";
import layout from "@voyzu/ui-layout/css-modules/detail.layout.module.css";
import detailStyles from "@voyzu/ui-style/css-modules/detail.module.css";
import typography from "@voyzu/ui-style/css-modules/typography.module.css";
import type { ItemListRow } from "../types/item-list.types";
import type { ItemCategoryOptionDto, ItemComponentDto, ItemPatchRequestDto, ItemResponseDto, PostingProfileOption } from "../types/item.types";
import { ITEM_UNIT_OPTIONS } from "../types/item-unit.options";
import styles from "./items.module.css";

const UNIT_OPTIONS = ITEM_UNIT_OPTIONS.map((unit) => ({ value: unit, label: unit }));
function isEmptyCustomValue(value: ItemResponseDto["customFields"][number]["value"] | undefined) {
  return value == null || value === "" || (Array.isArray(value) && value.length === 0);
}

export function ItemDetail({ item, categories, itemOptions, postingProfiles }: { item: ItemResponseDto; categories: ItemCategoryOptionDto[]; itemOptions: ItemListRow[]; postingProfiles: PostingProfileOption[]; }) {
  const router = useRouter(); const pathname = usePathname(); const [current, setCurrent] = useState(item);
  const [name, setName] = useState(item.name); const [description, setDescription] = useState(item.description); const [categoryId, setCategoryId] = useState(item.category ? String(item.category.id) : "");
  const [unit, setUnit] = useState(item.unit); const [quantityTracked, setQuantityTracked] = useState(item.quantityTracked); const [postingProfileId, setPostingProfileId] = useState(item.itemPostingCodeId ? String(item.itemPostingCodeId) : "");
  const [itemType, setItemType] = useState(item.itemType); const [components, setComponents] = useState<ItemComponentDto[]>(item.components); const [componentId, setComponentId] = useState(""); const [componentQuantity, setComponentQuantity] = useState("1");
  const [customValues, setCustomValues] = useState<Record<number, ItemResponseDto["customFields"][number]["value"]>>(Object.fromEntries(item.customFields.map((field) => [field.id, field.value])));
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [showDelete, setShowDelete] = useState(false); const [showNameWarning, setShowNameWarning] = useState(false); const [toast, setToast] = useState("");
  const validation = useFormValidation(() => ({ name: { label: "name", value: name, rules: [required()] }, unit: { label: "unit", value: unit, rules: [required()] } }));
  const request = async (path: string, init: RequestInit) => { setError(""); const response = await fetch(path, init); if (!response.ok) { const body = await response.json().catch(() => null) as { message?: string } | null; setError(body?.message ?? "The operation could not be completed"); return null; } return response; };
  const save = async () => { if (!validation.attempt()) return; const missingCustomFields = current.customFields.filter((field) => field.required && field.status === "ACTIVE" && isEmptyCustomValue(customValues[field.id])); if (missingCustomFields.length) { setError(`Complete required custom field${missingCustomFields.length === 1 ? "" : "s"}: ${missingCustomFields.map(({ name: fieldName }) => fieldName).join(", ")}`); return; }
    setSaving(true); try { const payload: ItemPatchRequestDto = { name: name.trim(), description: description.trim(), categoryId: categoryId ? Number(categoryId) : null, unit, quantityTracked,
      itemPostingCodeId: postingProfileId ? Number(postingProfileId) : null, itemType, components: itemType === "ASSEMBLY" ? components.map(({ itemId, quantity }) => ({ itemId, quantity })) : [],
      customFields: current.customFields.filter(({ status }) => status === "ACTIVE").map((field) => ({ customFieldId: field.id, value: customValues[field.id] ?? null })) };
    const response = await request(`/api/inventory/items/${encodeURIComponent(current.sku)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response) return;
    const changed = await response.json() as ItemResponseDto; setCurrent(changed); setComponents(changed.components); setCustomValues(Object.fromEntries(changed.customFields.map((field) => [field.id, field.value]))); setToast(`Item ${changed.sku} saved`); } finally { setSaving(false); } };
  const requestSave = () => { if (current.inUse && name.trim() !== current.name) setShowNameWarning(true); else void save(); };
  const transition = async (action: "activate" | "deactivate") => { const response = await request(`/api/inventory/items/${encodeURIComponent(current.sku)}/${action}`, { method: "POST" }); if (!response) return; const changed = await response.json() as ItemResponseDto; setCurrent(changed); setToast(`Item ${changed.sku} ${action}d`); };
  const remove = async () => { const response = await request(`/api/inventory/items/${encodeURIComponent(current.sku)}`, { method: "DELETE" }); if (!response) return; window.sessionStorage.setItem("inventory-items-toast", `Item ${current.sku} deleted`); router.push("/inventory/items"); router.refresh(); };
  const addComponent = () => { const candidate = itemOptions.find(({ id }) => String(id) === componentId); const quantity = Number(componentQuantity); if (!candidate || !Number.isFinite(quantity) || quantity <= 0) { setError("Select a component and enter a quantity greater than zero"); return; }
    if (components.some(({ itemId }) => itemId === candidate.id)) { setError(`${candidate.sku} is already a component`); return; }
    setComponents((currentComponents) => [...currentComponents, { itemId: candidate.id, sku: candidate.sku, name: candidate.name, quantity, unit: candidate.unit }]); setComponentId(""); setComponentQuantity("1"); setError(""); };
  const candidates = itemOptions.filter((candidate) => candidate.id !== current.id && candidate.itemType === "SINGLE_ITEM" && candidate.status === "ACTIVE" && !components.some(({ itemId }) => itemId === candidate.id));
  const details = <div className={styles.detailStack}><section className={detailStyles.card}><div className={detailStyles.cardHeader}><h2 className={`${typography.sectionHeading} ${detailStyles.cardHeaderTitle}`}>Item Details</h2><div className={detailStyles.cardHeaderActions}><Button variant="secondary" icon="save" disabled={saving} onClick={requestSave}>{saving ? "Saving..." : "Save"}</Button></div></div><div className={detailStyles.formGrid}>
    <div className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>SKU</label><Input value={current.sku} disabled /></div>
    <div className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>Name</label><Input value={name} invalid={validation.hasError("name")} onChange={(event) => setName(event.target.value)} /></div>
    <div className={`${detailStyles.fieldGroup} ${detailStyles.fieldFull}`}><label className={typography.fieldLabel}>Description</label><textarea className={styles.textarea} value={description} rows={3} onChange={(event) => setDescription(event.target.value)} /></div>
    <div className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>Category</label><SearchableSelect value={categoryId} onChange={setCategoryId} clearable options={categories.map((category) => ({ value: String(category.id), label: category.name, code: category.code }))} placeholder="Uncategorised" /></div>
    <div className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>Unit</label><SearchableSelect value={unit} onChange={setUnit} options={UNIT_OPTIONS} searchable={false} /></div>
    <label className={styles.checkboxField}><Checkbox checked={quantityTracked} onChange={setQuantityTracked} /><span>Quantity Tracked</span></label>
    <div className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>Financial Posting Profile</label><SearchableSelect value={postingProfileId} onChange={setPostingProfileId} clearable options={postingProfiles.filter((profile) => profile.status === "ACTIVE" || String(profile.id) === postingProfileId).map((profile) => ({ value: String(profile.id), label: profile.name, code: profile.code }))} placeholder={postingProfiles.length ? "Select a posting profile" : "Finance profiles unavailable"} disabled={!postingProfiles.length} /></div>
  </div></section></div>;
  const assembly = <div className={styles.detailStack}><section className={detailStyles.card}><div className={detailStyles.cardHeader}><h2 className={`${typography.sectionHeading} ${detailStyles.cardHeaderTitle}`}>Assembly Details</h2><div className={detailStyles.cardHeaderActions}><Button variant="secondary" icon="save" disabled={saving} onClick={requestSave}>{saving ? "Saving..." : "Save"}</Button></div></div><div className={detailStyles.formGrid}><div className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>Item Type</label><SearchableSelect value={itemType} onChange={(value) => setItemType(value as "SINGLE_ITEM" | "ASSEMBLY")} searchable={false} options={[{ value: "SINGLE_ITEM", label: "Single Item" }, { value: "ASSEMBLY", label: "Assembly (Multiple Items)" }]} /></div></div></section>
  {itemType === "ASSEMBLY" ? <section className={detailStyles.card}><div className={detailStyles.cardHeader}><h2 className={`${typography.sectionHeading} ${detailStyles.cardHeaderTitle}`}>Assembly Components</h2></div><div className={styles.componentAdder}><SearchableSelect value={componentId} onChange={setComponentId} options={candidates.map((candidate) => ({ value: String(candidate.id), label: candidate.name, code: candidate.sku }))} placeholder="Select component..." /><Input type="number" min="0.0001" step="0.0001" value={componentQuantity} onChange={(event) => setComponentQuantity(event.target.value)} /><Button variant="secondary" icon="add" onClick={addComponent}>Add Component</Button></div>
    <div className={detailStyles.tableWrap}><table className={detailStyles.table}><thead><tr><th>Item SKU</th><th>Item Name</th><th className={detailStyles.numericCell}>Quantity</th><th>Unit</th><th /></tr></thead><tbody>{components.length ? components.map((component) => <tr key={component.itemId}><td className={detailStyles.strongCell}>{component.sku}</td><td>{component.name}</td><td className={detailStyles.numericCell}>{component.quantity}</td><td>{component.unit}</td><td><Button variant="plain" icon="delete" title={`Remove ${component.sku}`} onClick={() => setComponents((values) => values.filter(({ itemId }) => itemId !== component.itemId))} /></td></tr>) : <tr><td colSpan={5} className={styles.emptyCell}>No components have been added.</td></tr>}</tbody></table></div>
  </section> : <section className={`${detailStyles.card} ${detailStyles.mutedCard}`}><div className={styles.assemblyNotice}><span className="material-symbols-outlined" aria-hidden="true">info</span><div><h3 className={typography.sectionHeading}>Assembly components do not apply</h3><p className={typography.bodyText}>Assembly details only apply to assemblies. Change Item Type to Assembly to define component items and quantities.</p></div></div></section>}</div>;
  const customFields = <section className={detailStyles.card}><div className={detailStyles.cardHeader}><h2 className={`${typography.sectionHeading} ${detailStyles.cardHeaderTitle}`}>Custom Fields</h2><Button variant="secondary" icon="save" disabled={saving || !current.customFields.some(({ status }) => status === "ACTIVE")} onClick={requestSave}>{saving ? "Saving..." : "Save"}</Button></div>
    {current.customFields.length ? <div className={detailStyles.formGrid}>{current.customFields.map((field) => { const disabled = field.status !== "ACTIVE"; const value = customValues[field.id]; const label = `${field.name}${field.required ? " *" : ""}`;
      if (field.dataType === "BOOLEAN") return <label key={field.id} className={styles.checkboxField}><Checkbox checked={value === true} disabled={disabled} onChange={(checked) => setCustomValues((values) => ({ ...values, [field.id]: checked }))} /><span>{label}</span></label>;
      if (field.dataType === "OPTION") return <div key={field.id} className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>{label}</label><SearchableSelect value={typeof value === "number" ? String(value) : ""} onChange={(selected) => setCustomValues((values) => ({ ...values, [field.id]: selected ? Number(selected) : null }))} clearable disabled={disabled} options={field.options.map((option) => ({ value: String(option.id), label: option.value }))} /></div>;
      if (field.dataType === "MULTIPLE_OPTIONS") return <div key={field.id} className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>{label}</label><SearchableSelect multiple value={Array.isArray(value) ? value.map(String) : []} onChange={(selected) => setCustomValues((values) => ({ ...values, [field.id]: selected.map(Number) }))} disabled={disabled} options={field.options.map((option) => ({ value: String(option.id), label: option.value }))} /></div>;
      return <div key={field.id} className={detailStyles.fieldGroup}><label className={typography.fieldLabel}>{label}</label><Input type={field.dataType === "NUMBER" ? "number" : field.dataType === "DATE" ? "date" : "text"} disabled={disabled} value={typeof value === "string" || typeof value === "number" ? value : ""} onChange={(event) => setCustomValues((values) => ({ ...values, [field.id]: field.dataType === "NUMBER" ? (event.target.value === "" ? null : Number(event.target.value)) : event.target.value }))} /></div>;
    })}</div> : <p className={typography.bodyText}>No item custom fields are configured for this organization.</p>}
  </section>;

  return <div className={`${layout.detailView} ${layout.detailViewWithStatusRail}`}><header className={layout.detailHeader}><div className={layout.slotBreadcrumb}><Breadcrumbs /></div><div className={layout.slotTitle}><div className={detailStyles.title}><div className={detailStyles.titleIcon}><span className={`material-symbols-outlined ${detailStyles.titleIconSymbol}`}>box</span></div><h1 className={`${typography.pageTitle} ${layout.pageTitleResponsive}`}>{name}</h1></div></div><div className={layout.slotActions}><div className={detailStyles.headerActions}><DetailBackButton fallbackHref="/inventory/items" /><div className={detailStyles.headerActionSeparator} /><Button variant="secondary" icon="check_circle" disabled={current.status === "ACTIVE"} onClick={() => { void transition("activate"); }}>Activate</Button><Button variant="secondary" icon="block" disabled={current.status === "INACTIVE"} onClick={() => { void transition("deactivate"); }}>Deactivate</Button><div className={detailStyles.headerActionSeparator} /><Button variant="danger" icon="delete" title={current.inUse ? "In-use items cannot be deleted" : "Delete item"} disabled={current.inUse} onClick={() => setShowDelete(true)} /></div></div><div className={layout.slotAlert}><ValidationAlert errors={[...validation.errors, ...(error ? [error] : [])]} visible={validation.showErrors || !!error} onDismiss={() => { validation.dismiss(); setError(""); }} /></div></header>
    <aside className={layout.statusSection}><div className={detailStyles.card}><label className={typography.fieldLabel}>Status</label><Badge variant="soft" size="x-large" color={current.status === "ACTIVE" ? "success" : "neutral"}>{current.status}</Badge>{current.inUse ? <Badge variant="soft" size="medium" color="success">IN USE</Badge> : null}</div><AuditPanel id={current.id} creationDate={current.audit.created.date} updatedDate={current.audit.updated.date} creationActorType={current.audit.created.actorType} creationUser={current.audit.created.user} updatedActorType={current.audit.updated.actorType} updatedUser={current.audit.updated.user} auditHref={(() => { const mutationId = current.audit.updated.mutationId ?? current.audit.created.mutationId; const filter = mutationId ? `mutationId=${encodeURIComponent(mutationId)}` : `entityType=item&entityId=${current.id}`; return detailLinkWithBackContext(`/settings/audit?${filter}`, "audit", pathname); })()} onNavigate={(href) => router.push(href)} /></aside>
    <main className={layout.mainSection}><TabGroup defaultKey="details" tabs={[{ key: "details", label: "Details", content: details }, { key: "assembly", label: "Assembly", content: assembly }, { key: "custom-fields", label: "Custom Fields", content: customFields }]} /></main>
    <ConfirmDialog isOpen={showDelete} title="Delete Item" message={`Permanently delete ${current.sku} — ${current.name}?`} confirmLabel="Delete" confirmVariant="danger" onClose={() => setShowDelete(false)} onConfirm={() => { void remove(); }} />
    <ConfirmDialog isOpen={showNameWarning} title="Rename In-use Item" message={`This item is in use. Changing its name may affect how it is recognised in existing inventory records. Continue?`} confirmLabel="Continue and Save" onClose={() => setShowNameWarning(false)} onConfirm={() => { setShowNameWarning(false); void save(); }} />
    <Toast isVisible={!!toast} onClose={() => setToast("")} message={toast} />
  </div>;
}
