export enum ComponentType {
  BANK_CASH = "BANK_CASH",
  CONTROL_ACCOUNT = "CONTROL_ACCOUNT",
  DIRECT_GL = "DIRECT_GL",
  ITEM_POSTING_PROFILE_CODE = "ITEM_POSTING_PROFILE_CODE",
  POSTING_CODE = "POSTING_CODE",
  SOURCE_DOCUMENT = "SOURCE_DOCUMENT",
}
