import {
  apBillCancellationPostingComponents as apBillCancellation,
  apBillPostingComponents as apBill,
  apCreditNotePostingComponents as apCreditNote,
  apOpeningBalancePostingComponents as apOpeningBalance,
  apPaymentApplicationPostingComponents as apPaymentApplication,
  apPaymentPostingComponents as apPayment,
  apRefundPostingComponents as apRefund,
  apWriteOffPostingComponents as apWriteOff,
  arCreditNotePostingComponents as arCreditNote,
  arInvoiceCancellationPostingComponents as arInvoiceCancellation,
  arInvoicePostingComponents as arInvoice,
  arOpeningBalancePostingComponents as arOpeningBalance,
  arReceiptApplicationPostingComponents as arReceiptApplication,
  arReceiptPostingComponents as arReceipt,
  arRefundPostingComponents as arRefund,
  arWriteOffPostingComponents as arWriteOff,
  inventoryAdjustmentPostingComponents as inventoryAdjustment,
  inventoryIssuePostingComponents as inventoryIssue,
  inventoryReceiptPostingComponents as inventoryReceipt,
  ledgerJournalPostingComponents as ledgerJournal,
  taxAdjustmentPostingComponents as taxAdjustment,
  taxPaymentPostingComponents as taxPayment,
  taxRefundPostingComponents as taxRefund,
} from "@voyzu-modules/core/financial-document-processing-engine/server";

const formulas: Record<string, string> = {
  AP_BILL: apBill.formula,
  AP_BILL_CANCELLATION: apBillCancellation.formula,
  AP_CREDIT_NOTE: apCreditNote.formula,
  AP_OPENING_BALANCE: apOpeningBalance.formula,
  AP_PAYMENT: apPayment.formula,
  AP_PAYMENT_APPLICATION: apPaymentApplication.formula,
  AP_REFUND: apRefund.formula,
  AP_WRITE_OFF: apWriteOff.formula,
  AR_CREDIT_NOTE: arCreditNote.formula,
  AR_INVOICE: arInvoice.formula,
  AR_INVOICE_CANCELLATION: arInvoiceCancellation.formula,
  AR_OPENING_BALANCE: arOpeningBalance.formula,
  AR_RECEIPT: arReceipt.formula,
  AR_RECEIPT_APPLICATION: arReceiptApplication.formula,
  AR_REFUND: arRefund.formula,
  AR_WRITE_OFF: arWriteOff.formula,
  INVENTORY_ADJUSTMENT: inventoryAdjustment.formula,
  INVENTORY_ISSUE: inventoryIssue.formula,
  INVENTORY_RECEIPT: inventoryReceipt.formula,
  LEDGER_JOURNAL: ledgerJournal.formula,
  TAX_ADJUSTMENT: taxAdjustment.formula,
  TAX_PAYMENT: taxPayment.formula,
  TAX_REFUND: taxRefund.formula,
};

export function postingFormulaForDocument(documentCode: string): string | null {
  return formulas[documentCode] ?? null;
}
