-- ============================================================
-- Dimension
-- Business domain: Company Financial Settings > Dimensions
-- ============================================================

CREATE TABLE IF NOT EXISTS dimension (
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_organization_id            BIGINT NOT NULL,
    code                  business_code NOT NULL,
    name                  display_name NOT NULL,
    status                active_status,

    creation_date         audit_timestamp,
    creation_actor_type   actor_type,
    creation_user_id      TEXT,
    creation_mutation_id UUID,
    updated_date          audit_timestamp,
    updated_actor_type    actor_type,
    updated_user_id       TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_dimension_company FOREIGN KEY (finance_organization_id) REFERENCES finance_organization(id) ON DELETE CASCADE,
    CONSTRAINT uq_dimension_company_code UNIQUE (finance_organization_id, code),
    CONSTRAINT uq_dimension_finance_organization_id UNIQUE (finance_organization_id, id)
);
