CREATE TABLE IF NOT EXISTS finance_inventory_processing_rule (
    id                         BIGINT PRIMARY KEY
                               GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    finance_organization_id    BIGINT NOT NULL,
    inventory_document_type    TEXT NOT NULL,
    reason_code                TEXT NOT NULL,
    direction                  TEXT NOT NULL,
    action                     TEXT NOT NULL,
    offset_gl_account_id       BIGINT,

    creation_date              audit_timestamp,
    creation_actor_type        actor_type,
    creation_user_id           TEXT,
    creation_mutation_id       UUID,
    updated_date               audit_timestamp,
    updated_actor_type         actor_type,
    updated_user_id            TEXT,
    updated_mutation_id        UUID,
    deletion_date              audit_timestamp,
    deletion_actor_type        actor_type,
    deletion_user_id           TEXT,
    deletion_mutation_id       UUID,

    CONSTRAINT fk_finance_inventory_processing_rule_organization
      FOREIGN KEY (finance_organization_id)
      REFERENCES finance_organization(id)
      ON DELETE CASCADE,

    CONSTRAINT fk_finance_inventory_processing_rule_offset_account
      FOREIGN KEY (finance_organization_id, offset_gl_account_id)
      REFERENCES gl_account(finance_organization_id, id),

    CONSTRAINT uq_finance_inventory_processing_rule
      UNIQUE (finance_organization_id, inventory_document_type, reason_code, direction),

    CONSTRAINT ck_finance_inventory_processing_rule_document_type
      CHECK (inventory_document_type IN ('RECEIPT', 'ISSUE', 'ADJUSTMENT')),

    CONSTRAINT ck_finance_inventory_processing_rule_reason_code
      CHECK (btrim(reason_code) <> ''),

    CONSTRAINT ck_finance_inventory_processing_rule_direction
      CHECK (direction IN ('INCREASE', 'DECREASE')),

    CONSTRAINT ck_finance_inventory_processing_rule_fixed_direction
      CHECK (
        inventory_document_type = 'ADJUSTMENT'
        OR (inventory_document_type = 'RECEIPT' AND direction = 'INCREASE')
        OR (inventory_document_type = 'ISSUE' AND direction = 'DECREASE')
      ),

    CONSTRAINT ck_finance_inventory_processing_rule_action
      CHECK (action IN (
        'CREATE_INVENTORY_ADJUSTMENT_JOURNAL',
        'CREATE_INVENTORY_RECEIPT_JOURNAL',
        'CREATE_INVENTORY_ISSUE_JOURNAL',
        'WAIT_FOR_MATCHED_DOCUMENT'
      )),

    CONSTRAINT ck_finance_inventory_processing_rule_offset_account
      CHECK (
        (action = 'WAIT_FOR_MATCHED_DOCUMENT' AND offset_gl_account_id IS NULL)
        OR
        (action <> 'WAIT_FOR_MATCHED_DOCUMENT' AND offset_gl_account_id IS NOT NULL)
      )
);
