CREATE TABLE IF NOT EXISTS inventory_ledger_entry_header (
    id                          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code                        TEXT NOT NULL UNIQUE,
    finance_company_id                  BIGINT NOT NULL,
    journal_header_id           BIGINT NOT NULL,
    source_document_type_code   business_code NOT NULL,
    document_id                 TEXT NOT NULL,
    description                 TEXT NOT NULL,
    memo                        TEXT,
    document_date               DATE NOT NULL,
    posting_date                DATE NOT NULL,
    financial_year_id           BIGINT NOT NULL,
    financial_period_id         BIGINT NOT NULL,
    base_currency_code          iso_currency_code NOT NULL,
    status                      TEXT NOT NULL DEFAULT 'POSTED' CHECK (status = 'POSTED'),

    creation_date               audit_timestamp,
    creation_actor_type         actor_type,
    creation_user_id            TEXT,
    creation_mutation_id UUID,

    updated_date                audit_timestamp,
    updated_actor_type          actor_type,
    updated_user_id             TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT fk_inventory_ledger_header_company          FOREIGN KEY (finance_company_id)                 REFERENCES finance_company(id),
    CONSTRAINT fk_inventory_ledger_header_journal          FOREIGN KEY (journal_header_id)          REFERENCES journal_header(id),
    CONSTRAINT fk_inventory_ledger_header_source_document  FOREIGN KEY (source_document_type_code) REFERENCES financial_document_type(code),
    CONSTRAINT fk_inventory_ledger_header_financial_year   FOREIGN KEY (financial_year_id)          REFERENCES fiscal_year(id),
    CONSTRAINT fk_inventory_ledger_header_financial_period FOREIGN KEY (financial_period_id)        REFERENCES fiscal_period(id),
    CONSTRAINT fk_inventory_ledger_header_base_currency    FOREIGN KEY (base_currency_code)         REFERENCES currency(code)
);
